## 1、local查询

### 1.1 模型配置

In [2]:
import os
from dotenv import load_dotenv

load_dotenv()

True

In [3]:
from openai import OpenAI
# 实例化客户端
client = OpenAI(    
                api_key=os.getenv("openai_api_key", None),
                base_url=os.getenv("base_url", None))

In [4]:
models_list = client.models.list()

In [5]:
models_list.data

[Model(id='deepseek-chat', created=None, object='model', owned_by='deepseek'),
 Model(id='deepseek-reasoner', created=None, object='model', owned_by='deepseek')]

In [6]:
# 调用 GPT-4o-mini 模型
response = client.chat.completions.create(
    model="deepseek-chat",
    messages=[
        {"role": "user", "content": "你好，好久不见!"}
    ]
)

In [7]:
# 输出生成的响应内容
print(response.choices[0].message.content)

你好！好久不见，很高兴再次见到你！最近过得怎么样？有什么想聊的吗？

In [8]:
from openai import OpenAI
# 实例化客户端
clientopenai = OpenAI(    
                api_key="sk-cRtxv5U9AdK45kVNr4InXs3oIUTnnb6L3H5xJ9AaAA7qUe53",
                base_url="http://chatapi.littlewheat.com/v1"
)
models_list = clientopenai.models.list()
models_list.data

[Model(id='chatgpt-4o-latest', created=1626777600, object='model', owned_by='openai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='chatgpt-4o-latest', parent=None),
 Model(id='claude-3-5-haiku-20241022', created=1626777600, object='model', owned_by='vertex-ai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='claude-3-5-haiku-20241022', parent=None),
 Model(id='claude-3-5-sonnet-20240620', created=1626777600, object='model', owned_by='vertex-ai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='claude-3-5-sonnet-20240620', parent=None),
 Model(id='claude-3-5-sonnet-20241022', created=1626777600, object='model', owned_by='vertex-ai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='claude-3-5-sonnet-20241022', parent=None),
 Model(id='claude-3-5-sonnet-all', created=1626777600, object='model', owned_by='custom', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='claude-3-5-sonnet-all', parent=None),
 Model(id='claude-3-7-sonnet-20250219', created=1626777600, object='model', owned_by='vertex-ai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='claude-3-7-sonnet-20250219', parent=None),
 Model(id='claude-3-7-sonnet-thinking', created=1626777600, object='model', owned_by='custom', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='claude-3-7-sonnet-thinking', parent=None),
 Model(id='claude-3-haiku-20240307', created=1626777600, object='model', owned_by='vertex-ai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='claude-3-haiku-20240307', parent=None),
 Model(id='claude-3-opus-20240229', created=1626777600, object='model', owned_by='vertex-ai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='claude-3-opus-20240229', parent=None),
 Model(id='claude-3.7-sonnet', created=1626777600, object='model', owned_by='custom', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='claude-3.7-sonnet', parent=None),
 Model(id='dall-e-2', created=1626777600, object='model', owned_by='custom', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='dall-e-2', parent=None),
 Model(id='dall-e-3', created=1626777600, object='model', owned_by='openai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='dall-e-3', parent=None),
 Model(id='deepseek-ai/DeepSeek-R1', created=1626777600, object='model', owned_by='custom', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='deepseek-ai/DeepSeek-R1', parent=None),
 Model(id='deepseek-ai/DeepSeek-V3', created=1626777600, object='model', owned_by='custom', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='deepseek-ai/DeepSeek-V3', parent=None),
 Model(id='deepseek-chat', created=1626777600, object='model', owned_by='deepseek', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='deepseek-chat', parent=None),
 Model(id='deepseek-coder', created=1626777600, object='model', owned_by='custom', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='deepseek-coder', parent=None),
 Model(id='deepseek-r1', created=1626777600, object='model', owned_by='volcengine', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='deepseek-r1', parent=None),
 Model(id='deepseek-r1-2025-01-20', created=1626777600, object='model', owned_by='custom', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='deepseek-r1-2025-01-20', parent=None),
 Model(id='deepseek-r1-searching', created=1626777600, object='model', owned_by='custom', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='deepseek-r1-searching', parent=None),
 Model(id='deepseek-reasoner', created=1626777600, object='model', owned_by='deepseek', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='deepseek-reasoner', parent=None),
 Model(id='deepseek-v3', created=1626777600, object='model', owned_by='volcengine', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='deepseek-v3', parent=None),
 Model(id='flux', created=1626777600, object='model', owned_by='custom', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='flux', parent=None),
 Model(id='gemini-2.0-flash-exp', created=1626777600, object='model', owned_by='vertex-ai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='gemini-2.0-flash-exp', parent=None),
 Model(id='gemini-2.0-flash-thinking-exp', created=1626777600, object='model', owned_by='vertex-ai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='gemini-2.0-flash-thinking-exp', parent=None),
 Model(id='gemini-2.0-flash-thinking-exp-1219', created=1626777600, object='model', owned_by='custom', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='gemini-2.0-flash-thinking-exp-1219', parent=None),
 Model(id='gemini-2.0-pro-exp-02-05', created=1626777600, object='model', owned_by='custom', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='gemini-2.0-pro-exp-02-05', parent=None),
 Model(id='glm-4-air', created=1626777600, object='model', owned_by='zhipu_4v', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='glm-4-air', parent=None),
 Model(id='gpt-3.5-turbo', created=1626777600, object='model', owned_by='openai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='gpt-3.5-turbo', parent=None),
 Model(id='gpt-3.5-turbo-0125', created=1626777600, object='model', owned_by='openai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='gpt-3.5-turbo-0125', parent=None),
 Model(id='gpt-3.5-turbo-0613', created=1626777600, object='model', owned_by='openai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='gpt-3.5-turbo-0613', parent=None),
 Model(id='gpt-3.5-turbo-1106', created=1626777600, object='model', owned_by='openai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='gpt-3.5-turbo-1106', parent=None),
 Model(id='gpt-3.5-turbo-16k', created=1626777600, object='model', owned_by='openai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='gpt-3.5-turbo-16k', parent=None),
 Model(id='gpt-3.5-turbo-16k-0613', created=1626777600, object='model', owned_by='openai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='gpt-3.5-turbo-16k-0613', parent=None),
 Model(id='gpt-3.5-turbo-instruct', created=1626777600, object='model', owned_by='openai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='gpt-3.5-turbo-instruct', parent=None),
 Model(id='gpt-4', created=1626777600, object='model', owned_by='openai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='gpt-4', parent=None),
 Model(id='gpt-4-0125-preview', created=1626777600, object='model', owned_by='openai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='gpt-4-0125-preview', parent=None),
 Model(id='gpt-4-0314', created=1626777600, object='model', owned_by='custom', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='gpt-4-0314', parent=None),
 Model(id='gpt-4-0613', created=1626777600, object='model', owned_by='openai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='gpt-4-0613', parent=None),
 Model(id='gpt-4-1106-preview', created=1626777600, object='model', owned_by='openai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='gpt-4-1106-preview', parent=None),
 Model(id='gpt-4-gizmo-*', created=1626777600, object='model', owned_by='custom', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='gpt-4-gizmo-*', parent=None),
 Model(id='gpt-4-turbo', created=1626777600, object='model', owned_by='openai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='gpt-4-turbo', parent=None),
 Model(id='gpt-4-turbo-preview', created=1626777600, object='model', owned_by='openai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='gpt-4-turbo-preview', parent=None),
 Model(id='gpt-4-vision-preview', created=1626777600, object='model', owned_by='openai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='gpt-4-vision-preview', parent=None),
 Model(id='gpt-4o', created=1626777600, object='model', owned_by='openai', permission=[{'id': 'modelperm-LwHkVFn8AcMItP432fKKDIKJ', 'object': 'model_permission', 'created': 1626777600, 'allow_create_engine': True, 'allow_sampling': True, 'allow_logprobs': True, 'allow_search_indices': False, 'allow_view': True, 'allow_fine_tuning': False, 'organization': '*', 'group': None, 'is_blocking': False}], root='gpt-4o', parent=None),

## 文件展示

In [9]:
import pandas as pd

In [10]:
documents = pd.read_parquet("./sushi/output/create_final_documents.parquet")

#### 1 documents

In [11]:
documents

,id,human_readable_id,title,text,text_unit_ids
0,15f30077a469a205b2919e1b476dbae05a1c156d5d8295...,1,sushi.txt,# 苏轼：北宋文坛的璀璨巨星\n苏轼，这位北宋时期的传奇人物，于宋景祐三年十二月十九日（10...,[9cf74fd1963f3ea256ff5e08d48961c31a129e528543f...

#### 2 text-unit

In [12]:
text_unit = pd.read_parquet("./sushi/output/create_final_text_units.parquet")

In [13]:
text_unit

,id,human_readable_id,text,n_tokens,document_ids,entity_ids,relationship_ids
0,9cf74fd1963f3ea256ff5e08d48961c31a129e528543fc...,1,# 苏轼：北宋文坛的璀璨巨星\n苏轼，这位北宋时期的传奇人物，于宋景祐三年十二月十九日（10...,1200,[15f30077a469a205b2919e1b476dbae05a1c156d5d829...,"[d6817101-c2bb-4e13-ae4e-298c7ea37548, 9a286aa...","[cceef94f-5251-4ef5-901a-247db7336939, 7a62731..."
1,a6053b30c0cdc69a23d7b0e55aa2c29a4200cf69ef4b9d...,2,��步天下！”\n\n在欧阳修的极力称赞下，苏轼声名鹊起，一时间成为京城的焦点人物。他的每一...,1200,[15f30077a469a205b2919e1b476dbae05a1c156d5d829...,"[d6817101-c2bb-4e13-ae4e-298c7ea37548, 9a286aa...","[cceef94f-5251-4ef5-901a-247db7336939, 01fa1b7..."
2,ad032814011ec3af535e738af040ecafe3572d4b86aeaf...,3,1077年）四月至元丰二年（1079年）三月，苏轼在徐州任知州。期间，黄河在曹村决口，洪水泛...,1200,[15f30077a469a205b2919e1b476dbae05a1c156d5d829...,"[d6817101-c2bb-4e13-ae4e-298c7ea37548, 97f69ad...","[a292cd7e-0794-48c2-9073-92c92207b9d0, 8be3f58..."
3,686ba4dd7e8a80c18f7e59e21bf5d4685c8016ec34e5c2...,4,山游览，触景生情，写下了《赤壁赋》《后赤壁赋》和《念奴娇·赤壁怀古》等千古名作，借景抒情，寄...,1200,[15f30077a469a205b2919e1b476dbae05a1c156d5d829...,"[d6817101-c2bb-4e13-ae4e-298c7ea37548, 97f69ad...","[a292cd7e-0794-48c2-9073-92c92207b9d0, b1c633c..."
4,83dd38f6b525caf8b64eb7a32627a5e614c27067736e19...,5,关注到杭州的水利问题。茅山有一条河专门容纳钱塘江潮水，盐桥有一条河专门容纳西湖水，但河道年久...,1200,[15f30077a469a205b2919e1b476dbae05a1c156d5d829...,"[d6817101-c2bb-4e13-ae4e-298c7ea37548, c8d9e60...","[01fa1b73-beee-4725-a6a0-5c5f1f260109, 58bf44c..."
5,ad70dd7af670a36d9182e17f7c6c4f8b9514ee09d17e8f...,6,�年（1093年）九月，苏轼出任定州知州。然而，这一年高太后去世，哲宗开始亲政，新党再度掌权...,1200,[15f30077a469a205b2919e1b476dbae05a1c156d5d829...,"[d6817101-c2bb-4e13-ae4e-298c7ea37548, ed966f2...","[bf90ae15-e97a-4f53-933b-e6d4d198b3fb, cfdc6e0..."
6,e7ca4da204cfa950606820f22ea8e2813bb033ec8340ef...,7,与哲思的交融\n苏轼的诗歌题材广泛，涵盖了社会现实、人生思考、自然景观等诸多方面。他对社会现...,1186,[15f30077a469a205b2919e1b476dbae05a1c156d5d829...,"[d6817101-c2bb-4e13-ae4e-298c7ea37548, eee46f1...","[6dfcf4cf-c671-4127-aca9-5153d1186a52, 4617984..."
7,a76034282881b48a0a48dfd1dbe4250763b7a86d11a7f4...,8,现柔情之词扩展为表现豪情之词，将表现爱情之词扩展为表现性情之词，使词像诗一样可以充分展现作者...,86,[15f30077a469a205b2919e1b476dbae05a1c156d5d829...,[d6817101-c2bb-4e13-ae4e-298c7ea37548],None

In [16]:
len(text_unit["entity_ids"][0])

15

In [17]:
text_unit["relationship_ids"][0]

array(['cceef94f-5251-4ef5-901a-247db7336939',
       '7a62731d-ce21-41cf-861d-ca26873e3775',
       '01fa1b73-beee-4725-a6a0-5c5f1f260109',
       '1e70c77f-94de-49f8-9fb3-5518ae68943c',
       'ff6da3ba-49f2-411f-a1b3-0c493d588705',
       '27de1cce-8e72-4ee4-a670-ef38a571bb54',
       'cffa3b08-a53d-469f-b91f-5370cfe06983',
       '9bc3e00f-85f8-4f41-a3e2-b79a43eecf7a',
       'db89e21d-5c6a-41bb-bf79-422da4a18b38',
       '4cfb6958-9d66-41eb-923e-af742a768bc7',
       'a6a77886-3f7d-414a-87d3-ab272738223a',
       'ab2fa619-0972-4908-abc0-45ae844c12a4',
       '94b28e1e-ebd7-466a-a987-3641116a88bf',
       'ed0f52c9-05b5-4b9b-a5c7-9a518cd3dc05'], dtype=object)

#### 3 entities

In [18]:
entities = pd.read_parquet("./sushi/output/create_final_entities.parquet")

In [19]:
entities

,id,human_readable_id,title,type,description,text_unit_ids
0,d6817101-c2bb-4e13-ae4e-298c7ea37548,0,苏轼,PERSON,苏轼，字子瞻，号东坡居士，是中国北宋时期著名的文学家、政治家、书法家和诗人。他出生于眉州眉山...,[9cf74fd1963f3ea256ff5e08d48961c31a129e528543f...
1,9a286aa6-750f-49c6-882f-d233e3f391ae,1,苏洵,PERSON,苏洵是北宋时期的文学家、政治家和古文名家，学识渊博。他是著名文学家苏轼和苏辙的父亲，在苏轼幼...,[9cf74fd1963f3ea256ff5e08d48961c31a129e528543f...
2,6b01d1a6-6c20-4a0f-88e5-1c08c296498c,2,程氏,PERSON,程氏是苏轼的母亲，知书达理，曾以东汉名士范滂的事迹激励苏轼，让他从小就懂得砥砺名节。,[9cf74fd1963f3ea256ff5e08d48961c31a129e528543f...
3,c8d9e601-e081-4666-9266-99064818eac9,3,苏辙,PERSON,苏辙是北宋时期的文学家和政治家，同时也是著名文学家苏轼的弟弟。他与苏轼一同随父亲苏洵赴京城参...,[9cf74fd1963f3ea256ff5e08d48961c31a129e528543f...
4,401b1d0b-9003-4537-aba3-fbc16cd87358,4,欧阳修,PERSON,欧阳修是北宋时期的著名文学家和政治家，与苏轼有着深厚的师友情谊。他曾担任苏轼科举考试的主考官...,[9cf74fd1963f3ea256ff5e08d48961c31a129e528543f...
...,...,...,...,...,...,...
115,d3faaa37-dbda-42ea-a564-6d57fcde70a3,115,《和子由渑池怀旧》,EVENT,《和子由渑池怀旧》是苏轼的一首诗，将人生的经历比作雪泥鸿爪，表达了对人生无常的感慨，展现了苏...,[e7ca4da204cfa950606820f22ea8e2813bb033ec8340e...
116,4b5bf23b-de25-46a5-94cb-5f8c0062c0f4,116,词,EVENT,苏轼在词的创作上取得了突破性成就，打破了词为“艳科”的传统格局，提高了词的文学地位，使词从音...,[e7ca4da204cfa950606820f22ea8e2813bb033ec8340e...
117,8f42f7ff-3085-4fd6-bfca-2e7e66182583,117,庐山,GEO,庐山是苏轼在《题西林壁》中描写的自然景观，象征着人们对事物认识的局限性。,[e7ca4da204cfa950606820f22ea8e2813bb033ec8340e...
118,1a8b054a-cdfd-4ba7-83a2-0b151436b1e0,118,渑池,GEO,渑池是苏轼在《和子由渑池怀旧》中提到的地点，象征着人生无常和回忆。,[e7ca4da204cfa950606820f22ea8e2813bb033ec8340e...
119,64890e97-9f54-4571-8d92-8ee09c429991,119,诗,EVENT,苏轼的诗歌题材广泛，涵盖了社会现实、人生思考和自然景观，表现出深刻的思想内涵和高超的艺术技巧。,[e7ca4da204cfa950606820f22ea8e2813bb033ec8340e...

In [21]:
entities["type"].unique()

array(['PERSON', 'GEO', 'EVENT', '', 'ORGANIZATION'], dtype=object)

In [22]:
entities["text_unit_ids"][0]

array(['9cf74fd1963f3ea256ff5e08d48961c31a129e528543fca92d8c490f36b7071d745fafa6bef834398e3e7912ab577bf5df3f4315a4103705fc2306ad65f346b1',
       'a6053b30c0cdc69a23d7b0e55aa2c29a4200cf69ef4b9d8515a119279de1cbdf9c38a98de07af8a0bca0cf6531047381698b37f693e765f91467c411a3accaf5',
       'ad032814011ec3af535e738af040ecafe3572d4b86aeafb073499f4643bfb4a5b2b9034cdf3d7f16e710dc09f40ddecf3e13fbd19be29c07aa5c76aacb4edf6b',
       '686ba4dd7e8a80c18f7e59e21bf5d4685c8016ec34e5c2e92113c036ede23de046f4a8fa07efebb741b31039934c2329b1fb5e2371f291a695777ddece3c53e5',
       '83dd38f6b525caf8b64eb7a32627a5e614c27067736e19da1dcdbcce52847fd2510259d6459ffcc92eeac7e73f2eb1f8b8ff9caba9420af2020ee9d9db3ec90e',
       'ad70dd7af670a36d9182e17f7c6c4f8b9514ee09d17e8f15ccb0193ce1b029a98c38b30b7b6b5febe9d449cdcd134740398a28f1e96e38854b5dee68aeaa5f31',
       'e7ca4da204cfa950606820f22ea8e2813bb033ec8340ef3b511dcd87e5b74b211317cfd2512fd6e7f0fc75978f38308db7f5e4f12f7bdf3460e3f08287e2fe4b',
       'a76034282881b48a0a48dfd1dbe4250763b7a86d11a7f496e06dd2abb57a1e87d1510069e2e9a040b6ffed00a91e5623de4f1f1fa24637715e8bf2a909bf9592'],
      dtype=object)

#### 4 nodes

In [25]:
nodes = pd.read_parquet("./sushi/output/create_final_nodes.parquet")

In [26]:
nodes

,id,human_readable_id,title,community,level,degree,x,y
0,d6817101-c2bb-4e13-ae4e-298c7ea37548,0,苏轼,1,0,117,0,0
1,9a286aa6-750f-49c6-882f-d233e3f391ae,1,苏洵,5,0,2,0,0
2,6b01d1a6-6c20-4a0f-88e5-1c08c296498c,2,程氏,1,0,1,0,0
3,c8d9e601-e081-4666-9266-99064818eac9,3,苏辙,1,0,1,0,0
4,401b1d0b-9003-4537-aba3-fbc16cd87358,4,欧阳修,1,0,1,0,0
...,...,...,...,...,...,...,...,...
115,d3faaa37-dbda-42ea-a564-6d57fcde70a3,115,《和子由渑池怀旧》,0,0,2,0,0
116,4b5bf23b-de25-46a5-94cb-5f8c0062c0f4,116,词,1,0,1,0,0
117,8f42f7ff-3085-4fd6-bfca-2e7e66182583,117,庐山,2,0,2,0,0
118,1a8b054a-cdfd-4ba7-83a2-0b151436b1e0,118,渑池,0,0,2,0,0
119,64890e97-9f54-4571-8d92-8ee09c429991,119,诗,1,0,1,0,0

In [27]:
nodes["community"].unique()

array([1, 5, 3, 4, 6, 2, 0])

#### 5 relationship

In [23]:
relationship = pd.read_parquet("./sushi/output/create_final_relationships.parquet")

In [24]:
relationship

,id,human_readable_id,source,target,description,weight,combined_degree,text_unit_ids
0,cceef94f-5251-4ef5-901a-247db7336939,0,苏轼,苏洵,苏轼是苏洵的儿子。苏洵在苏轼幼年时悉心传授学识与品行，对苏轼的成长和教育起到了重要作用。后来...,17.0,119,[9cf74fd1963f3ea256ff5e08d48961c31a129e528543f...
1,7a62731d-ce21-41cf-861d-ca26873e3775,1,苏轼,程氏,苏轼是程氏的儿子，程氏曾以东汉名士范滂的事迹激励苏轼,8.0,118,[9cf74fd1963f3ea256ff5e08d48961c31a129e528543f...
2,01fa1b73-beee-4725-a6a0-5c5f1f260109,2,苏轼,苏辙,苏轼和苏辙是兄弟，他们一同随父亲苏洵赴京城参加科举考试，并在京城声名大噪。后来，因母亲病故，...,22.0,118,[9cf74fd1963f3ea256ff5e08d48961c31a129e528543f...
3,1e70c77f-94de-49f8-9fb3-5518ae68943c,3,苏轼,欧阳修,苏轼和欧阳修是中国宋代著名的文学家和政治家。欧阳修不仅是苏轼的师友，还极力称赞苏轼的才华，并...,14.0,118,[9cf74fd1963f3ea256ff5e08d48961c31a129e528543f...
4,ff6da3ba-49f2-411f-a1b3-0c493d588705,4,苏轼,梅尧臣,梅尧臣是苏轼科举考试的小试官，对苏轼的文章高度赏识,7.0,118,[9cf74fd1963f3ea256ff5e08d48961c31a129e528543f...
...,...,...,...,...,...,...,...,...
121,bdfc7ae4-3066-4526-aa97-bcfde5dae18b,121,苏轼,庐山,苏轼在《题西林壁》中描写了庐山，揭示了人们对事物认识的局限性,6.0,119,[e7ca4da204cfa950606820f22ea8e2813bb033ec8340e...
122,6c72ab2b-72e1-4f86-b787-576fad12c2b5,122,苏轼,渑池,苏轼在《和子由渑池怀旧》中提到了渑池，表达了对人生无常的感慨,6.0,119,[e7ca4da204cfa950606820f22ea8e2813bb033ec8340e...
123,e4e8e8cd-3fb3-4be2-adf0-501ffd3501a2,123,苏轼,诗,苏轼创作了大量诗歌，涵盖了社会现实、人生思考和自然景观，表现出深刻的思想内涵,8.0,118,[e7ca4da204cfa950606820f22ea8e2813bb033ec8340e...
124,c5a65905-4bd6-4354-a0bf-5abbdb643b57,124,《题西林壁》,庐山,《题西林壁》描写了庐山，揭示了人们对事物认识的局限性,7.0,4,[e7ca4da204cfa950606820f22ea8e2813bb033ec8340e...
125,46a3aea9-f522-4008-9c46-e3ce2d73c7c6,125,《和子由渑池怀旧》,渑池,《和子由渑池怀旧》提到了渑池，表达了对人生无常的感慨,1.0,4,[e7ca4da204cfa950606820f22ea8e2813bb033ec8340e...

#### 6 communities

In [28]:
communities = pd.read_parquet("./sushi/output/create_final_communities.parquet")

In [29]:
communities

,id,human_readable_id,community,parent,level,title,entity_ids,relationship_ids,text_unit_ids,period,size
0,2edad02c-6e9f-4755-aabf-98590e0cc2f7,0,0,-1,0,Community 0,"[d3faaa37-dbda-42ea-a564-6d57fcde70a3, 1a8b054...",[46a3aea9-f522-4008-9c46-e3ce2d73c7c6],[e7ca4da204cfa950606820f22ea8e2813bb033ec8340e...,2025-03-18,2
1,d72df65f-1c88-466e-b549-f018dab3d3f1,1,1,-1,0,Community 1,"[d6817101-c2bb-4e13-ae4e-298c7ea37548, da9d0d4...","[01fa1b73-beee-4725-a6a0-5c5f1f260109, 02957d9...",[686ba4dd7e8a80c18f7e59e21bf5d4685c8016ec34e5c...,2025-03-18,108
2,4c44c71c-c407-4c3a-beeb-9d2f52a98a30,2,2,-1,0,Community 2,"[acc673a2-57eb-4c56-9039-18a24c96b68a, 8f42f7f...",[c5a65905-4bd6-4354-a0bf-5abbdb643b57],[e7ca4da204cfa950606820f22ea8e2813bb033ec8340e...,2025-03-18,2
3,05fad614-2c82-4624-8990-2b5ecae90f8b,3,3,-1,0,Community 3,"[19a60489-70d2-4f47-a3b0-50ce5e50f240, 4f5e361...",[df9a4836-f6b0-4e23-96ed-f6e7ecd0c3a6],[a6053b30c0cdc69a23d7b0e55aa2c29a4200cf69ef4b9...,2025-03-18,2
4,ade8635f-b983-4e2d-9d87-6dce7bbadee0,4,4,-1,0,Community 4,"[e87adc90-e2f7-4658-90ff-38ffc33a7461, 45dc92d...",[1f861709-adfa-47c8-ad39-4dd8426dc765],[686ba4dd7e8a80c18f7e59e21bf5d4685c8016ec34e5c...,2025-03-18,2
5,5726f768-c61b-4916-8872-fd791cea8652,5,5,-1,0,Community 5,"[468e7fcb-0735-4270-9036-daaff0c5f4c5, 9a286aa...",[2d99b29b-7833-4d84-b3ae-c0e5177105b0],[a6053b30c0cdc69a23d7b0e55aa2c29a4200cf69ef4b9...,2025-03-18,2
6,ff14188a-2fa3-4636-996f-adbe2f1cb10c,6,6,-1,0,Community 6,"[8ae6da10-72fc-49e8-9511-a392328da85b, 634beaa...",[a03550b8-94e1-4582-b98f-fd43cb2b5ede],[686ba4dd7e8a80c18f7e59e21bf5d4685c8016ec34e5c...,2025-03-18,2

In [35]:
communities["entity_ids"][1]

array(['d6817101-c2bb-4e13-ae4e-298c7ea37548',
       'da9d0d4f-c485-484a-b8c1-bb25de7479ef',
       'ed6d11b7-8d28-49be-a26a-5c0b0220d7f9',
       '3ae53b3d-5486-408d-8bae-cc472c4f3f74',
       '88181efc-a94d-4010-9a4d-81d81f95cf37',
       '2e4eb370-777a-4880-a77e-d48158f960d9',
       'eb781db6-ddef-4801-8135-c17a9a17a322',
       'd44bd6d9-ae2b-45e1-933c-9e3a29848b0a',
       '795b778b-59a0-4c89-a446-764fc018a928',
       'a06b2ca9-b54c-4bef-ab5b-6462a9d0dfe4',
       '8566ad62-b17f-4c3e-9d49-34b7bcf08c84',
       '27f82579-bfdf-4258-9b9c-d898c36e4acc',
       '4523374f-22e6-4efd-905b-25da6c0f6306',
       '7ba4d3c9-7f11-4abe-b82d-6d799d2dcdbe',
       '8eabd7a6-fc1f-46f6-8c88-8d6e2217685f',
       '2f7d94f2-8fc9-4b57-91f6-10255e6c770b',
       '984a0f8b-0ca0-4c36-a6f5-e2a3298fe3e3',
       '33de1482-fd5a-4262-bbd9-14e3dd92ae96',
       '0fb3373f-1e64-407f-a43e-f4dc74c73bec',
       '4af60a0e-5ac8-48c1-a205-9d433b9c6480',
       '186e653b-3b94-4cc5-b103-dbd122e3cb8d',
       'e4730bd5-c693-4484-bf62-1ec598789298',
       '6b51bc97-5ea1-45a3-a8f1-84f43d11f6f4',
       '9215016f-28ef-49be-9173-464336e3bccf',
       'eee46f12-f8dd-4023-92d7-de42bdb64a03',
       'dda76aae-6efe-4830-a39e-d3999ecf8a28',
       '69ba05f2-5724-4bde-872f-9af5c2c797dc',
       'f0dcd66a-dcdc-4da9-aca7-f079bbf3a95f',
       '460d1746-d2fc-46a6-b269-e13c5dfaf4f7',
       '05dd8ea4-9a6e-4c9d-b14a-bd47bbb53ea2',
       '630e3308-3ee4-44e1-adec-b77d3c1304fa',
       '2ed33803-9550-49ed-9918-1c5056469578',
       '26ea85b2-af62-416b-9232-4c92adf0170a',
       'ae5e9d46-1ae1-4146-9042-e830262e732f',
       '69d2017c-66dc-4b21-97a1-51943d5042f5',
       '644d0a29-88c7-4303-adbe-9d3e74b51b3d',
       'f06543f6-4ced-4ca1-80fb-cbc1f79e5c15',
       '62cb2478-948a-42bc-b5cf-f71e8f1e40c0',
       'be141698-0484-4528-824d-2d08806d7a8d',
       'f8900886-d794-4fb5-855a-591886110a53',
       '91916ee4-4d00-4b8f-bd68-73b3f5011202',
       '7b7537e3-d961-41dc-855c-082a78da05d0',
       'e84b1ddd-aef6-4977-a3a0-57fd31e4ac66',
       '88d4f2f4-25e9-4803-9f8d-37b7cac40fc0',
       '2cbb6148-4588-4252-895f-377a654f86c3',
       '1cbf0bc6-b92e-42e8-9d66-fcc22ad37ff2',
       'ed966f25-e4d2-4872-873f-84e61d3b65d9',
       '47b7f67f-a5a7-41eb-9d94-4ec0dcfce689',
       'fe0ae751-4480-446d-8141-40a5475c7359',
       '95f89601-d679-42b0-8957-b408b4c419dd',
       '3780bb09-3236-4299-afd6-9b5e4b304417',
       '295b1088-26d4-4716-8c2f-3cab80d81274',
       'f5ee4bc5-b581-48b2-982b-b0b7aa5e897d',
       'fcd7d6d2-8249-4095-adf5-5021d9c6020a',
       '33f68902-d29e-4de8-b254-8bfb15130df2',
       '1357a5cc-7c0c-442d-a567-13008c4867f6',
       '4ea5acde-a892-430c-b05c-6637b3d545e9',
       'fb2dccf3-200a-47d3-9f70-04d014f8cb09',
       'af49742b-a87b-4788-b24b-268eea5b08cd',
       'f36d732b-158c-4e8a-ab87-658bbee33aaf',
       'ce84caba-5d47-4ebe-b17e-8c9bbab5db28',
       '401b1d0b-9003-4537-aba3-fbc16cd87358',
       '4e0f4b4d-344d-460f-aa5a-51a6f3d1a506',
       'aa01c621-d432-4025-8f43-246bb32301be',
       'ec39ca5f-17de-4b3d-bdc6-c866399b7c0c',
       '0ff95c30-9bcb-470d-bdfa-1db11dffa258',
       '95b42648-3aab-4124-9dde-60a24933c2c7',
       '97f69ad4-277d-4e1f-8262-533d61c3f8e7',
       'f60512ad-6a28-43eb-b192-fd4e711df24f',
       'b9af9bbd-1a73-4ae3-a621-8c38274e3ce9',
       '90cbea9e-fa31-41cc-9bca-b0dd9733001a',
       'f5aae915-b421-4056-81aa-dabfac234835',
       '04e32a1e-17cc-4b68-88da-8a10693b5576',
       '97dd7c25-9325-4d79-8a21-faf98c56651d',
       'a1ff8285-bcc1-4f0b-8ffd-d48f2c7eab73',
       'f8fde2db-049e-4160-bf13-981acf0132f5',
       '4d49e702-3314-493b-8e4c-e5f7972c0a04',
       'ccb549da-2651-49c6-b097-06da516019c6',
       '83a6e54d-f4dd-4eac-9149-9f8d8add8244',
       'c08711c2-80fb-4490-aa0b-e98a243bc59d',
       'ea27e22f-b08e-4d63-9bc0-a50dc903c4e9',
       '4bcc51d0-cd80-47bb-b3ea-61a2ce74dfa4',
       '6b01d1a6-6c20-4a0f-88e5-1c08c296498c',
       '277d348e-be20-4248-b9d5-a2672123e069',
       '319a4740-8554-4f51-91dc-d1778717091e',
       '5140f6f0-03fe-4cbb-9111-16be4d8ecd32',
       'b9dc0116-c49d-4f14-bff7-e2f7f39671fa',
       'f79b66c5-07ba-4b40-933b-8c59f2884c2c',
       'dd237930-ecff-4cea-b5ec-73ebc58ccd74',
       '88ed08eb-25a9-4aa2-a8e9-0cac2e4c5d6e',
       'b6233100-21d8-408a-889f-62bd90a8b5ff',
       'c8d9e601-e081-4666-9266-99064818eac9',
       'f6ba8396-1ab1-4c7b-a5a0-3812da389c00',
       'bb027f97-384e-48ee-ba34-ace078902b1a',
       '4b5bf23b-de25-46a5-94cb-5f8c0062c0f4',
       '64890e97-9f54-4571-8d92-8ee09c429991',
       '8401af09-654c-4a81-90e0-575ed1d21eed',
       'c5b459ce-5e48-4684-9af8-70deed1afb49',
       'e5145e5e-5220-4479-a5ea-a61341727b46',
       'f48ca015-53a0-4de6-9a90-b9a76c7186e9',
       '7e4d5fdf-d48f-4a4f-a10a-1d4a037d349c',
       '4d14ec58-377d-4a58-b7d5-bcf26848190c',
       '86990694-0ea5-4b0a-926e-bd3fd2ee4208',
       '706cc70a-68bd-4512-9b67-16d8369c7adb',
       '643f6aa0-d986-4edf-9fd4-5c24cb097ec2',
       'b4a4bde3-39da-462a-9337-b5c77f293055',
       '59233fd4-5e11-4ca1-abf4-36e282920548',
       '77ee01fc-4e90-4471-8f05-2c5f094fcd18'], dtype=object)

In [32]:
len(communities["entity_ids"][1])

108

In [36]:
communities["relationship_ids"][1]

array(['01fa1b73-beee-4725-a6a0-5c5f1f260109',
       '02957d98-3942-4701-b13d-a496773b3719',
       '06da1bf1-4967-4526-827c-9d0f316d7be2',
       '0833401a-09b1-4e8d-89fe-9e9567455cb3',
       '09e28792-1535-4a83-b1aa-5c6ab63f8f90',
       '13805db0-ddfc-454f-a9bd-c0bbce10563e',
       '1636d827-5552-48d5-8e3b-8bfbd96d2ad3',
       '18a83cfc-b97e-4c8a-9bd0-4b020ffd1c42',
       '1e70c77f-94de-49f8-9fb3-5518ae68943c',
       '21a58ae2-3026-419d-96c2-823243f77227',
       '22c19894-b0fe-429f-a89a-83b6f5fb34e9',
       '27de1cce-8e72-4ee4-a670-ef38a571bb54',
       '2a2760d0-bb55-4696-9a2e-81fc96e0131b',
       '2e1f35d0-617a-40f5-a13f-ac7652c919ea',
       '3234865d-dd82-4ba8-87b1-721880efeab6',
       '324776a3-a5e6-490f-a153-22d364d89909',
       '329aac51-577d-4af0-ad9f-7235082173e0',
       '33945359-cf1c-4859-adaf-efe85f3fc8e8',
       '3972a944-ef9a-4929-ae01-d34f8b862ae4',
       '3e287cff-d64f-4092-a9b6-5db9992bb55c',
       '4092093b-0f38-4b09-915b-806198a1e9a4',
       '41c53d5c-1e90-4805-b671-6dc7bd9589a5',
       '42850f8b-bf2e-43a8-aa2c-e3c9148ae80a',
       '434549c5-f089-4518-ab0a-91bf32ad2392',
       '4587cf83-b1dc-458a-9654-d7debe99ef80',
       '4cb94bd2-ddf8-4e07-95eb-57200897346e',
       '4cfb6958-9d66-41eb-923e-af742a768bc7',
       '53900eba-0811-4386-a1fa-0a6e5b485cb6',
       '58bf44c3-3673-4b8d-98b0-f84f2fea6a30',
       '591932e3-a6bf-4d3f-886e-6551d5f19f47',
       '599b59cf-0947-41f7-9eef-163f122ba211',
       '5e5f2894-b82d-4781-be21-5a767d651809',
       '6032a0d2-3b0c-4e76-8110-683cb03e5522',
       '60374d1b-6661-49e4-b5ab-a5be835b48ed',
       '6274fddd-f799-4d36-a177-31879d65f6c6',
       '62dd472b-47bf-4701-bdb9-dcc5d94dfc5a',
       '65516b11-295e-4539-846f-e88ba74d7090',
       '6554e796-0a46-4c3f-85cf-76ce9d40cf69',
       '67d30adc-864f-4ee4-8b1f-6dcb4341eee6',
       '6dfcf4cf-c671-4127-aca9-5153d1186a52',
       '6f927e14-4ceb-4e4d-824c-c13c6c0660ca',
       '72955e5b-84f0-4cf8-9c97-91870001510a',
       '736e35d9-9ac7-49b7-aa61-eae7e0259df9',
       '76dd8027-6712-408f-93a8-da6832df5dcb',
       '76e1cfed-2cb6-4dd3-84d9-d515ff72a506',
       '778118a3-4572-46f4-8777-efc5776ca4a1',
       '7794e3cc-554b-4e51-bd20-22ef8dcfd6d1',
       '799b9a14-a6f9-4be5-b870-efc02cd4ade5',
       '7a62731d-ce21-41cf-861d-ca26873e3775',
       '7a90b50a-e31e-4f88-9836-7a1c9108e14f',
       '8474613e-9f49-403d-9e4f-fe43b86d3e98',
       '84cd812b-81d7-48d4-98c5-a62c9cc4406e',
       '87578454-fe7b-4281-b007-39c985123734',
       '8b3d73e9-12de-495b-916b-d3091149cc4f',
       '8be3f583-4d1f-416e-8e84-b874a1e254c4',
       '8f3ff660-b182-4c96-874a-992eb6fb5798',
       '934c5c9f-df6e-49a8-b4ee-137aeac58b6e',
       '93502d1c-5d3a-4986-848e-7ae3e77158c4',
       '9364b006-adfc-4f46-828f-2a9265d577da',
       '94adbd51-5f1f-495a-92b3-1926e3b14c27',
       '94b28e1e-ebd7-466a-a987-3641116a88bf',
       '96f85d3c-7ec6-4201-b3c4-c346b469f155',
       '9858d84d-ae64-424b-b8a2-e9b2ec8fe0e2',
       '98890e68-9500-4074-8707-eaa74dc2103c',
       '9b4fb0e5-24c4-4af5-8b16-04d6d7592e82',
       '9bc3e00f-85f8-4f41-a3e2-b79a43eecf7a',
       '9d87ab88-50a3-4dc6-b08e-c88334a04c65',
       'a0afbbca-d279-4ba4-b37a-07c505d4bc62',
       'a292cd7e-0794-48c2-9073-92c92207b9d0',
       'a2e33e05-33b3-4c94-b442-2da303d1ee09',
       'a3a3cdca-4054-4ccc-bac9-f2c792266f24',
       'a57706e8-0e97-4782-bd69-7b9b6b302f03',
       'a59622a1-3874-4d31-94a2-d1af0968a874',
       'a670b82b-e89a-47ce-8ca4-7239ed499ae6',
       'a6a77886-3f7d-414a-87d3-ab272738223a',
       'ab0af662-bdda-4cbb-93c6-9261dd8b64fd',
       'ab2fa619-0972-4908-abc0-45ae844c12a4',
       'ac605f82-4247-42a2-aa83-7e582d757c46',
       'ad83ccb0-5364-46fa-af0c-d32de8716ce8',
       'ae2a17c7-5e25-4aca-b86e-426e323629d9',
       'afc42c74-5145-4f12-9cd5-ea170efcbcce',
       'b0ea91a0-844a-493d-96c3-0b02c22f2d1d',
       'b11cbfca-fb14-4dc1-b127-556bea92f174',
       'b1c633c3-19b5-480f-acbe-3ff3650526ab',
       'b55b29ee-f359-4112-b1cc-da93ef6b9ac9',
       'b633cca5-78f2-4f56-b861-00ef359c3553',
       'b66f1a26-3537-4c6b-8d5c-e7b52353feaa',
       'bb65620a-dad5-4a10-a837-caba6dc9b489',
       'bf90ae15-e97a-4f53-933b-e6d4d198b3fb',
       'c51e824a-00f0-43b1-93e4-83c26bf98724',
       'c5e95fd6-2be7-4c39-a70a-634edf3b34ed',
       'cd093ba0-b42a-4cf3-a64b-76cf27a302f9',
       'cfdc6e02-1f4d-444d-a65e-c161402c6396',
       'cffa3b08-a53d-469f-b91f-5370cfe06983',
       'd0378f97-7742-4669-90fc-7cf13415a0af',
       'db89e21d-5c6a-41bb-bf79-422da4a18b38',
       'dc9729b5-da21-4a96-92b5-bb032e8a9e37',
       'dd55710c-0140-4ac2-84a8-28de9b42bfc5',
       'e4e8e8cd-3fb3-4be2-adf0-501ffd3501a2',
       'e7f810e1-f3dc-41f4-93a8-f16c8f41947b',
       'e96684a5-dc22-44f6-b190-619220dff603',
       'ed0f52c9-05b5-4b9b-a5c7-9a518cd3dc05',
       'ed9ed094-fad3-4efc-a9e6-72a75319f652',
       'efc958a0-651f-40b3-9d6d-5ed1dbc426fb',
       'f108182d-1f18-49c2-9b21-7dd1aaf51b37',
       'fb5c1152-d3e0-4617-aa62-02f89c9d3701',
       'fc531fd7-173b-4c69-a6f6-2cf150271176',
       'ff6da3ba-49f2-411f-a1b3-0c493d588705'], dtype=object)

In [37]:
len(communities["relationship_ids"][1])

108

In [38]:
communities["text_unit_ids"][1]

array(['686ba4dd7e8a80c18f7e59e21bf5d4685c8016ec34e5c2e92113c036ede23de046f4a8fa07efebb741b31039934c2329b1fb5e2371f291a695777ddece3c53e5',
       '83dd38f6b525caf8b64eb7a32627a5e614c27067736e19da1dcdbcce52847fd2510259d6459ffcc92eeac7e73f2eb1f8b8ff9caba9420af2020ee9d9db3ec90e',
       '9cf74fd1963f3ea256ff5e08d48961c31a129e528543fca92d8c490f36b7071d745fafa6bef834398e3e7912ab577bf5df3f4315a4103705fc2306ad65f346b1',
       'a6053b30c0cdc69a23d7b0e55aa2c29a4200cf69ef4b9d8515a119279de1cbdf9c38a98de07af8a0bca0cf6531047381698b37f693e765f91467c411a3accaf5',
       'ad032814011ec3af535e738af040ecafe3572d4b86aeafb073499f4643bfb4a5b2b9034cdf3d7f16e710dc09f40ddecf3e13fbd19be29c07aa5c76aacb4edf6b',
       'ad70dd7af670a36d9182e17f7c6c4f8b9514ee09d17e8f15ccb0193ce1b029a98c38b30b7b6b5febe9d449cdcd134740398a28f1e96e38854b5dee68aeaa5f31',
       'e7ca4da204cfa950606820f22ea8e2813bb033ec8340ef3b511dcd87e5b74b211317cfd2512fd6e7f0fc75978f38308db7f5e4f12f7bdf3460e3f08287e2fe4b'],
      dtype=object)

#### 7 communities_report

In [39]:
communities_report = pd.read_parquet("./sushi/output/create_final_community_reports.parquet")

In [40]:
communities_report

,id,human_readable_id,community,parent,level,title,summary,full_content,rank,rank_explanation,findings,full_content_json,period,size
0,f7b6802ac0dd49c4b889be8c3b6fef8b,0,0,-1,0,苏轼与渑池的哲思,该社区围绕苏轼及其诗作《和子由渑池怀旧》展开，渑池作为诗中的地点，象征着人生无常和回忆。苏轼...,# 苏轼与渑池的哲思\n\n该社区围绕苏轼及其诗作《和子由渑池怀旧》展开，渑池作为诗中的地点...,3.5,影响严重性评分为中等，因为虽然苏轼的诗作对文学和哲学有重要影响，但其直接的社会或政治影响有限。,[{'explanation': '渑池在苏轼的《和子由渑池怀旧》中被提及，象征着人生无常和...,"{\n ""title"": ""苏轼与渑池的哲思"",\n ""summary"": ""该...",2025-03-18,2
1,191a1af6d82746edb2797f528d58d1d1,1,1,-1,0,苏轼及其文学与政治影响,本报告聚焦于北宋时期的文学家、政治家苏轼及其相关实体，包括其家族成员、师友、政治对手以及其文...,# 苏轼及其文学与政治影响\n\n本报告聚焦于北宋时期的文学家、政治家苏轼及其相关实体，包括...,8.5,苏轼作为中国文学史上的重要人物，其文学成就和政治活动对后世产生了深远的影响，因此其影响严重性...,[{'explanation': '苏轼是中国北宋时期的著名文学家，其诗词、散文和书法作品广...,"{\n ""title"": ""苏轼及其文学与政治影响"",\n ""summary"":...",2025-03-18,108
2,ecf0cc5fb8e9419e81f459f9cdfd29c5,2,2,-1,0,庐山与《题西林壁》,该社区围绕庐山和苏轼的诗《题西林壁》展开，庐山作为自然景观在诗中象征着人们对事物认识的局限性...,# 庐山与《题西林壁》\n\n该社区围绕庐山和苏轼的诗《题西林壁》展开，庐山作为自然景观在诗...,3.5,影响严重性评分为中等，因为虽然社区围绕文化和哲学主题，但其对人们认识事物的启示具有深远影响。,[{'explanation': '庐山在苏轼的《题西林壁》中被描绘为象征人们对事物认识局限...,"{\n ""title"": ""庐山与《题西林壁》"",\n ""summary"": ""...",2025-03-18,2
3,67ccb5d11dde47f3a22554ad1f59b584,3,3,-1,0,谢景温与北宋御史,该社区围绕谢景温与北宋御史的关系展开。谢景温是北宋时期的御史，受王安石指使在宋神宗面前诋毁苏...,# 谢景温与北宋御史\n\n该社区围绕谢景温与北宋御史的关系展开。谢景温是北宋时期的御史，受...,7.5,影响严重性评分较高，因为这一事件揭示了北宋时期政治斗争的复杂性，对苏轼的职业生涯产生了重大影响。,[{'explanation': '谢景温是北宋时期的御史，受王安石指使在宋神宗面前诋毁苏轼...,"{\n ""title"": ""谢景温与北宋御史"",\n ""summary"": ""该...",2025-03-18,2
4,eeb3de1e2a404985b6b956378d8b4122,4,4,-1,0,West Lake and Su Shi,"The community centers around West Lake, a reno...",# West Lake and Su Shi\n\nThe community center...,7.5,The impact severity rating is high due to the ...,[{'explanation': 'West Lake is not only a natu...,"{\n ""title"": ""West Lake and Su Shi"",\n ""...",2025-03-18,2
5,64aa845d7cec48ce8dc9b7a4ef414351,5,5,-1,0,苏洵与秘书省,该社区围绕苏洵和秘书省两个关键实体展开。苏洵是北宋时期的文学家、政治家和古文名家，学识渊博，...,# 苏洵与秘书省\n\n该社区围绕苏洵和秘书省两个关键实体展开。苏洵是北宋时期的文学家、政治...,7.5,影响严重性评分为7.5，因为苏洵在文学和政治领域的成就及其与秘书省的关系对北宋文坛和政治领域...,[{'explanation': '苏洵是北宋时期的文学家、政治家和古文名家，学识渊博。他在...,"{\n ""title"": ""苏洵与秘书省"",\n ""summary"": ""该社区...",2025-03-18,2
6,3986dc8429974b63b40fabae83c71044,6,6,-1,0,茅山与钱塘江,该社区围绕茅山和钱塘江展开，钱塘江是杭州附近的一条主要河流，以其壮观的潮汐现象而闻名。茅山河...,# 茅山与钱塘江\n\n该社区围绕茅山和钱塘江展开，钱塘江是杭州附近的一条主要河流，以其壮观...,6.5,影响严重性评分为中等偏高，因为钱塘江和茅山在地理、历史和文化上对杭州地区有深远影响。,[{'explanation': '钱塘江是杭州附近的一条主要河流，以其壮观的潮汐现象而闻名...,"{\n ""title"": ""茅山与钱塘江"",\n ""summary"": ""该社区...",2025-03-18,2

In [42]:
print(communities_report["full_content"][1])

# 苏轼及其文学与政治影响

本报告聚焦于北宋时期的文学家、政治家苏轼及其相关实体，包括其家族成员、师友、政治对手以及其文学创作的重要地点。苏轼不仅在文学上成就斐然，还在政治上有诸多建树，其生平和作品对后世产生了深远的影响。

## 苏轼的文学成就

苏轼是中国北宋时期的著名文学家，其诗词、散文和书法作品广受赞誉。他的文学作品不仅展现了深刻的思想内涵和高超的艺术技巧，还对后世文学产生了深远的影响。苏轼在黄州期间创作的《赤壁赋》、《后赤壁赋》和《念奴娇·赤壁怀古》等作品，至今仍被视为中国文学史上的经典之作。[Data: Entities (0); Relationships (43, 44, 45)]

## 苏轼的政治生涯

苏轼在北宋时期担任多个地方官职，关心百姓疾苦，致力于救灾和水利工程。然而，因反对王安石变法，苏轼的仕途坎坷，多次调任地方官职。尽管如此，他在徐州任职期间领导百姓抗洪救灾，保全了徐州城，展现了其卓越的领导能力和为民服务的精神。[Data: Entities (0, 20, 24, 25); Relationships (19, 24, 25)]

## 苏轼与王安石的关系

苏轼与王安石是北宋时期的两位著名政治家和文学家。王安石是新党的领袖，推行了一系列变法政策，而苏轼作为旧党的代表人物之一，与王安石在政见上产生了严重分歧。尽管两人在政治上存在对立，王安石曾上书为苏轼求情，显示出他对苏轼的尊重和对其才华的认可。[Data: Entities (0, 15); Relationships (14)]

## 苏轼的家族影响

苏轼出生于名门，其父亲苏洵是古文名家，母亲程氏知书达理。苏洵在苏轼幼年时悉心传授学识与品行，对苏轼的成长和教育起到了重要作用。苏轼的弟弟苏辙也是北宋时期的文学家和政治家，兄弟二人在科举、仕途以及家庭责任方面有着紧密的联系和相互影响。[Data: Entities (0, 2, 3); Relationships (0, 1, 2)]

## 苏轼的师友情谊

苏轼与欧阳修、梅尧臣等北宋时期的文学家和政治家有着深厚的师友情谊。欧阳修不仅是苏轼的师友，还极力称赞苏轼的才华，并推荐他参加制科考试。梅尧臣是苏轼科举考试的小试官，对苏轼的文章高度赏识。这些师友情谊对苏轼的文学成就和仕途发展起到了重要的推动作用。[Data: Entities (0, 4, 5); Relationships (3, 4)]

In [43]:
communities_report["rank_explanation"][1]

'苏轼作为中国文学史上的重要人物，其文学成就和政治活动对后世产生了深远的影响，因此其影响严重性评分较高。'

In [44]:
communities_report["findings"][1]

array([{'explanation': '苏轼是中国北宋时期的著名文学家，其诗词、散文和书法作品广受赞誉。他的文学作品不仅展现了深刻的思想内涵和高超的艺术技巧，还对后世文学产生了深远的影响。苏轼在黄州期间创作的《赤壁赋》、《后赤壁赋》和《念奴娇·赤壁怀古》等作品，至今仍被视为中国文学史上的经典之作。[Data: Entities (0); Relationships (43, 44, 45)]', 'summary': '苏轼的文学成就'},
       {'explanation': '苏轼在北宋时期担任多个地方官职，关心百姓疾苦，致力于救灾和水利工程。然而，因反对王安石变法，苏轼的仕途坎坷，多次调任地方官职。尽管如此，他在徐州任职期间领导百姓抗洪救灾，保全了徐州城，展现了其卓越的领导能力和为民服务的精神。[Data: Entities (0, 20, 24, 25); Relationships (19, 24, 25)]', 'summary': '苏轼的政治生涯'},
       {'explanation': '苏轼与王安石是北宋时期的两位著名政治家和文学家。王安石是新党的领袖，推行了一系列变法政策，而苏轼作为旧党的代表人物之一，与王安石在政见上产生了严重分歧。尽管两人在政治上存在对立，王安石曾上书为苏轼求情，显示出他对苏轼的尊重和对其才华的认可。[Data: Entities (0, 15); Relationships (14)]', 'summary': '苏轼与王安石的关系'},
       {'explanation': '苏轼出生于名门，其父亲苏洵是古文名家，母亲程氏知书达理。苏洵在苏轼幼年时悉心传授学识与品行，对苏轼的成长和教育起到了重要作用。苏轼的弟弟苏辙也是北宋时期的文学家和政治家，兄弟二人在科举、仕途以及家庭责任方面有着紧密的联系和相互影响。[Data: Entities (0, 2, 3); Relationships (0, 1, 2)]', 'summary': '苏轼的家族影响'},
       {'explanation': '苏轼与欧阳修、梅尧臣等北宋时期的文学家和政治家有着深厚的师友情谊。欧阳修不仅是苏轼的师友，还极力称赞苏轼的才华，并推荐他参加制科考试。梅尧臣是苏轼科举考试的小试官，对苏轼的文章高度赏识。这些师友情谊对苏轼的文学成就和仕途发展起到了重要的推动作用。[Data: Entities (0, 4, 5); Relationships (3, 4)]', 'summary': '苏轼的师友情谊'}],
      dtype=object)

In [46]:
print(communities_report["full_content_json"][1])

{
    "title": "苏轼及其文学与政治影响",
    "summary": "本报告聚焦于北宋时期的文学家、政治家苏轼及其相关实体，包括其家族成员、师友、政治对手以及其文学创作的重要地点。苏轼不仅在文学上成就斐然，还在政治上有诸多建树，其生平和作品对后世产生了深远的影响。",
    "findings": [
        {
            "summary": "苏轼的文学成就",
            "explanation": "苏轼是中国北宋时期的著名文学家，其诗词、散文和书法作品广受赞誉。他的文学作品不仅展现了深刻的思想内涵和高超的艺术技巧，还对后世文学产生了深远的影响。苏轼在黄州期间创作的《赤壁赋》、《后赤壁赋》和《念奴娇·赤壁怀古》等作品，至今仍被视为中国文学史上的经典之作。[Data: Entities (0); Relationships (43, 44, 45)]"
        },
        {
            "summary": "苏轼的政治生涯",
            "explanation": "苏轼在北宋时期担任多个地方官职，关心百姓疾苦，致力于救灾和水利工程。然而，因反对王安石变法，苏轼的仕途坎坷，多次调任地方官职。尽管如此，他在徐州任职期间领导百姓抗洪救灾，保全了徐州城，展现了其卓越的领导能力和为民服务的精神。[Data: Entities (0, 20, 24, 25); Relationships (19, 24, 25)]"
        },
        {
            "summary": "苏轼与王安石的关系",
            "explanation": "苏轼与王安石是北宋时期的两位著名政治家和文学家。王安石是新党的领袖，推行了一系列变法政策，而苏轼作为旧党的代表人物之一，与王安石在政见上产生了严重分歧。尽管两人在政治上存在对立，王安石曾上书为苏轼求情，显示出他对苏轼的尊重和对其才华的认可。[Data: Entities (0, 15); Relationships (14)]"
        },
        {
            "summary": "苏轼的家族影响",
            "explanation": "苏轼出生于名门，其父亲苏洵是古文名家，母亲程氏知书达理。苏洵在苏轼幼年时悉心传授学识与品行，对苏轼的成长和教育起到了重要作用。苏轼的弟弟苏辙也是北宋时期的文学家和政治家，兄弟二人在科举、仕途以及家庭责任方面有着紧密的联系和相互影响。[Data: Entities (0, 2, 3); Relationships (0, 1, 2)]"
        },
        {
            "summary": "苏轼的师友情谊",
            "explanation": "苏轼与欧阳修、梅尧臣等北宋时期的文学家和政治家有着深厚的师友情谊。欧阳修不仅是苏轼的师友，还极力称赞苏轼的才华，并推荐他参加制科考试。梅尧臣是苏轼科举考试的小试官，对苏轼的文章高度赏识。这些师友情谊对苏轼的文学成就和仕途发展起到了重要的推动作用。[Data: Entities (0, 4, 5); Relationships (3, 4)]"
        }
    ],
    "rating": 8.5,
    "rating_explanation": "苏轼作为中国文学史上的重要人物，其文学成就和政治活动对后世产生了深远的影响，因此其影响严重性评分较高。"
}

### 1.2 查询

#### 1.2.1 local

In [47]:
import os

import pandas as pd
import tiktoken

from graphrag.query.context_builder.entity_extraction import EntityVectorStoreKey
from graphrag.query.indexer_adapters import (
    read_indexer_covariates,
    read_indexer_entities,
    read_indexer_relationships,
    read_indexer_reports,
    read_indexer_text_units,
)
from graphrag.query.llm.oai.chat_openai import ChatOpenAI
from graphrag.query.llm.oai.embedding import OpenAIEmbedding
from graphrag.query.llm.oai.typing import OpenaiApiType
from graphrag.query.question_gen.local_gen import LocalQuestionGen
from graphrag.query.structured_search.local_search.mixed_context import (
    LocalSearchMixedContext,
)
from graphrag.query.structured_search.local_search.search import LocalSearch
from graphrag.vector_stores.lancedb import LanceDBVectorStore

c:\ProgramData\anaconda3\envs\graphrag\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [48]:
text_unit_df = pd.read_parquet("./sushi/output/create_final_text_units.parquet")
text_units = read_indexer_text_units(text_unit_df)

print(f"Text unit records: {len(text_unit_df)}")
text_unit_df.head()

Text unit records: 8

,id,human_readable_id,text,n_tokens,document_ids,entity_ids,relationship_ids
0,9cf74fd1963f3ea256ff5e08d48961c31a129e528543fc...,1,# 苏轼：北宋文坛的璀璨巨星\n苏轼，这位北宋时期的传奇人物，于宋景祐三年十二月十九日（10...,1200,[15f30077a469a205b2919e1b476dbae05a1c156d5d829...,"[d6817101-c2bb-4e13-ae4e-298c7ea37548, 9a286aa...","[cceef94f-5251-4ef5-901a-247db7336939, 7a62731..."
1,a6053b30c0cdc69a23d7b0e55aa2c29a4200cf69ef4b9d...,2,��步天下！”\n\n在欧阳修的极力称赞下，苏轼声名鹊起，一时间成为京城的焦点人物。他的每一...,1200,[15f30077a469a205b2919e1b476dbae05a1c156d5d829...,"[d6817101-c2bb-4e13-ae4e-298c7ea37548, 9a286aa...","[cceef94f-5251-4ef5-901a-247db7336939, 01fa1b7..."
2,ad032814011ec3af535e738af040ecafe3572d4b86aeaf...,3,1077年）四月至元丰二年（1079年）三月，苏轼在徐州任知州。期间，黄河在曹村决口，洪水泛...,1200,[15f30077a469a205b2919e1b476dbae05a1c156d5d829...,"[d6817101-c2bb-4e13-ae4e-298c7ea37548, 97f69ad...","[a292cd7e-0794-48c2-9073-92c92207b9d0, 8be3f58..."
3,686ba4dd7e8a80c18f7e59e21bf5d4685c8016ec34e5c2...,4,山游览，触景生情，写下了《赤壁赋》《后赤壁赋》和《念奴娇·赤壁怀古》等千古名作，借景抒情，寄...,1200,[15f30077a469a205b2919e1b476dbae05a1c156d5d829...,"[d6817101-c2bb-4e13-ae4e-298c7ea37548, 97f69ad...","[a292cd7e-0794-48c2-9073-92c92207b9d0, b1c633c..."
4,83dd38f6b525caf8b64eb7a32627a5e614c27067736e19...,5,关注到杭州的水利问题。茅山有一条河专门容纳钱塘江潮水，盐桥有一条河专门容纳西湖水，但河道年久...,1200,[15f30077a469a205b2919e1b476dbae05a1c156d5d829...,"[d6817101-c2bb-4e13-ae4e-298c7ea37548, c8d9e60...","[01fa1b73-beee-4725-a6a0-5c5f1f260109, 58bf44c..."

In [49]:
nodes_df = pd.read_parquet("./sushi/output/create_final_nodes.parquet")
entitys_df = pd.read_parquet("./sushi/output/create_final_entities.parquet")

entities = read_indexer_entities(nodes_df, entitys_df,None)

In [50]:
print(f"Entity count: {len(nodes_df)}")
nodes_df.head()

Entity count: 120

,id,human_readable_id,title,community,level,degree,x,y
0,d6817101-c2bb-4e13-ae4e-298c7ea37548,0,苏轼,1,0,117,0,0
1,9a286aa6-750f-49c6-882f-d233e3f391ae,1,苏洵,5,0,2,0,0
2,6b01d1a6-6c20-4a0f-88e5-1c08c296498c,2,程氏,1,0,1,0,0
3,c8d9e601-e081-4666-9266-99064818eac9,3,苏辙,1,0,1,0,0
4,401b1d0b-9003-4537-aba3-fbc16cd87358,4,欧阳修,1,0,1,0,0

In [51]:
entitys_df

,id,human_readable_id,title,type,description,text_unit_ids
0,d6817101-c2bb-4e13-ae4e-298c7ea37548,0,苏轼,PERSON,苏轼，字子瞻，号东坡居士，是中国北宋时期著名的文学家、政治家、书法家和诗人。他出生于眉州眉山...,[9cf74fd1963f3ea256ff5e08d48961c31a129e528543f...
1,9a286aa6-750f-49c6-882f-d233e3f391ae,1,苏洵,PERSON,苏洵是北宋时期的文学家、政治家和古文名家，学识渊博。他是著名文学家苏轼和苏辙的父亲，在苏轼幼...,[9cf74fd1963f3ea256ff5e08d48961c31a129e528543f...
2,6b01d1a6-6c20-4a0f-88e5-1c08c296498c,2,程氏,PERSON,程氏是苏轼的母亲，知书达理，曾以东汉名士范滂的事迹激励苏轼，让他从小就懂得砥砺名节。,[9cf74fd1963f3ea256ff5e08d48961c31a129e528543f...
3,c8d9e601-e081-4666-9266-99064818eac9,3,苏辙,PERSON,苏辙是北宋时期的文学家和政治家，同时也是著名文学家苏轼的弟弟。他与苏轼一同随父亲苏洵赴京城参...,[9cf74fd1963f3ea256ff5e08d48961c31a129e528543f...
4,401b1d0b-9003-4537-aba3-fbc16cd87358,4,欧阳修,PERSON,欧阳修是北宋时期的著名文学家和政治家，与苏轼有着深厚的师友情谊。他曾担任苏轼科举考试的主考官...,[9cf74fd1963f3ea256ff5e08d48961c31a129e528543f...
...,...,...,...,...,...,...
115,d3faaa37-dbda-42ea-a564-6d57fcde70a3,115,《和子由渑池怀旧》,EVENT,《和子由渑池怀旧》是苏轼的一首诗，将人生的经历比作雪泥鸿爪，表达了对人生无常的感慨，展现了苏...,[e7ca4da204cfa950606820f22ea8e2813bb033ec8340e...
116,4b5bf23b-de25-46a5-94cb-5f8c0062c0f4,116,词,EVENT,苏轼在词的创作上取得了突破性成就，打破了词为“艳科”的传统格局，提高了词的文学地位，使词从音...,[e7ca4da204cfa950606820f22ea8e2813bb033ec8340e...
117,8f42f7ff-3085-4fd6-bfca-2e7e66182583,117,庐山,GEO,庐山是苏轼在《题西林壁》中描写的自然景观，象征着人们对事物认识的局限性。,[e7ca4da204cfa950606820f22ea8e2813bb033ec8340e...
118,1a8b054a-cdfd-4ba7-83a2-0b151436b1e0,118,渑池,GEO,渑池是苏轼在《和子由渑池怀旧》中提到的地点，象征着人生无常和回忆。,[e7ca4da204cfa950606820f22ea8e2813bb033ec8340e...
119,64890e97-9f54-4571-8d92-8ee09c429991,119,诗,EVENT,苏轼的诗歌题材广泛，涵盖了社会现实、人生思考和自然景观，表现出深刻的思想内涵和高超的艺术技巧。,[e7ca4da204cfa950606820f22ea8e2813bb033ec8340e...

In [52]:
description_embedding_store = LanceDBVectorStore(
    collection_name="default-entity-description",
)
description_embedding_store.connect(db_uri="./sushi/output/lancedb/")

In [54]:
relationship_df = pd.read_parquet("./sushi/output/create_final_relationships.parquet")
relationships = read_indexer_relationships(relationship_df)

print(f"Relationship count: {len(relationship_df)}")
relationship_df.head()

Relationship count: 126

,id,human_readable_id,source,target,description,weight,combined_degree,text_unit_ids
0,cceef94f-5251-4ef5-901a-247db7336939,0,苏轼,苏洵,苏轼是苏洵的儿子。苏洵在苏轼幼年时悉心传授学识与品行，对苏轼的成长和教育起到了重要作用。后来...,17.0,119,[9cf74fd1963f3ea256ff5e08d48961c31a129e528543f...
1,7a62731d-ce21-41cf-861d-ca26873e3775,1,苏轼,程氏,苏轼是程氏的儿子，程氏曾以东汉名士范滂的事迹激励苏轼,8.0,118,[9cf74fd1963f3ea256ff5e08d48961c31a129e528543f...
2,01fa1b73-beee-4725-a6a0-5c5f1f260109,2,苏轼,苏辙,苏轼和苏辙是兄弟，他们一同随父亲苏洵赴京城参加科举考试，并在京城声名大噪。后来，因母亲病故，...,22.0,118,[9cf74fd1963f3ea256ff5e08d48961c31a129e528543f...
3,1e70c77f-94de-49f8-9fb3-5518ae68943c,3,苏轼,欧阳修,苏轼和欧阳修是中国宋代著名的文学家和政治家。欧阳修不仅是苏轼的师友，还极力称赞苏轼的才华，并...,14.0,118,[9cf74fd1963f3ea256ff5e08d48961c31a129e528543f...
4,ff6da3ba-49f2-411f-a1b3-0c493d588705,4,苏轼,梅尧臣,梅尧臣是苏轼科举考试的小试官，对苏轼的文章高度赏识,7.0,118,[9cf74fd1963f3ea256ff5e08d48961c31a129e528543f...

In [53]:
report_df = pd.read_parquet("./sushi/output/create_final_community_reports.parquet")
reports = read_indexer_reports(report_df, nodes_df, None)

print(f"Report records: {len(report_df)}")
report_df.head()

Report records: 7

,id,human_readable_id,community,parent,level,title,summary,full_content,rank,rank_explanation,findings,full_content_json,period,size
0,f7b6802ac0dd49c4b889be8c3b6fef8b,0,0,-1,0,苏轼与渑池的哲思,该社区围绕苏轼及其诗作《和子由渑池怀旧》展开，渑池作为诗中的地点，象征着人生无常和回忆。苏轼...,# 苏轼与渑池的哲思\n\n该社区围绕苏轼及其诗作《和子由渑池怀旧》展开，渑池作为诗中的地点...,3.5,影响严重性评分为中等，因为虽然苏轼的诗作对文学和哲学有重要影响，但其直接的社会或政治影响有限。,[{'explanation': '渑池在苏轼的《和子由渑池怀旧》中被提及，象征着人生无常和...,"{\n ""title"": ""苏轼与渑池的哲思"",\n ""summary"": ""该...",2025-03-18,2
1,191a1af6d82746edb2797f528d58d1d1,1,1,-1,0,苏轼及其文学与政治影响,本报告聚焦于北宋时期的文学家、政治家苏轼及其相关实体，包括其家族成员、师友、政治对手以及其文...,# 苏轼及其文学与政治影响\n\n本报告聚焦于北宋时期的文学家、政治家苏轼及其相关实体，包括...,8.5,苏轼作为中国文学史上的重要人物，其文学成就和政治活动对后世产生了深远的影响，因此其影响严重性...,[{'explanation': '苏轼是中国北宋时期的著名文学家，其诗词、散文和书法作品广...,"{\n ""title"": ""苏轼及其文学与政治影响"",\n ""summary"":...",2025-03-18,108
2,ecf0cc5fb8e9419e81f459f9cdfd29c5,2,2,-1,0,庐山与《题西林壁》,该社区围绕庐山和苏轼的诗《题西林壁》展开，庐山作为自然景观在诗中象征着人们对事物认识的局限性...,# 庐山与《题西林壁》\n\n该社区围绕庐山和苏轼的诗《题西林壁》展开，庐山作为自然景观在诗...,3.5,影响严重性评分为中等，因为虽然社区围绕文化和哲学主题，但其对人们认识事物的启示具有深远影响。,[{'explanation': '庐山在苏轼的《题西林壁》中被描绘为象征人们对事物认识局限...,"{\n ""title"": ""庐山与《题西林壁》"",\n ""summary"": ""...",2025-03-18,2
3,67ccb5d11dde47f3a22554ad1f59b584,3,3,-1,0,谢景温与北宋御史,该社区围绕谢景温与北宋御史的关系展开。谢景温是北宋时期的御史，受王安石指使在宋神宗面前诋毁苏...,# 谢景温与北宋御史\n\n该社区围绕谢景温与北宋御史的关系展开。谢景温是北宋时期的御史，受...,7.5,影响严重性评分较高，因为这一事件揭示了北宋时期政治斗争的复杂性，对苏轼的职业生涯产生了重大影响。,[{'explanation': '谢景温是北宋时期的御史，受王安石指使在宋神宗面前诋毁苏轼...,"{\n ""title"": ""谢景温与北宋御史"",\n ""summary"": ""该...",2025-03-18,2
4,eeb3de1e2a404985b6b956378d8b4122,4,4,-1,0,West Lake and Su Shi,"The community centers around West Lake, a reno...",# West Lake and Su Shi\n\nThe community center...,7.5,The impact severity rating is high due to the ...,[{'explanation': 'West Lake is not only a natu...,"{\n ""title"": ""West Lake and Su Shi"",\n ""...",2025-03-18,2

In [55]:
llm = ChatOpenAI(
    api_key=os.getenv("openai_api_key", None),
    model="deepseek-chat",
    api_base=os.getenv("base_url", None),
    api_type=OpenaiApiType.OpenAI,  
    max_retries=20,
)

token_encoder = tiktoken.get_encoding("cl100k_base")

text_embedder = OpenAIEmbedding(
    api_key="sk-cRtxv5U9AdK45kVNr4InXs3oIUTnnb6L3H5xJ9AaAA7qUe53",
    api_base="http://chatapi.littlewheat.com/v1",
    api_type=OpenaiApiType.OpenAI,
    model="text-embedding-3-large",
    deployment_name="text-embedding-3-large",
    max_retries=20,
)

In [56]:
context_builder = LocalSearchMixedContext(
    community_reports=reports,
    text_units=text_units,
    entities=entities,
    relationships=relationships,
    covariates=None,
    entity_text_embeddings=description_embedding_store,
    embedding_vectorstore_key=EntityVectorStoreKey.ID,  
    text_embedder=text_embedder,
    token_encoder=token_encoder,
)

In [58]:
local_context_params = {
    "text_unit_prop": 0.5,
    "community_prop": 0.1,
    "conversation_history_max_turns": 5,
    "conversation_history_user_turns_only": True,
    "top_k_mapped_entities": 10,
    "top_k_relationships": 10,
    "include_entity_rank": True,
    "include_relationship_weight": True,
    "include_community_rank": True,
    "return_candidate_context": True,
    "embedding_vectorstore_key": EntityVectorStoreKey.ID,  
    "max_tokens": 12_000, 
}

llm_params = {
    "max_tokens": 2_000, 
    "temperature": 0.0,
}

In [59]:
search_engine = LocalSearch(
    llm=llm,
    context_builder=context_builder,
    token_encoder=token_encoder,
    llm_params=llm_params,
    context_builder_params=local_context_params,
    response_type="multiple paragraphs", 
)

In [60]:
result = await search_engine.asearch("评价下苏轼")

In [62]:
result.response

'苏轼（1037-1101），字子瞻，号东坡居士，是中国北宋时期著名的文学家、政治家、书法家和诗人。他的一生充满了传奇色彩，不仅在文学上成就斐然，还在政治上有诸多建树，其生平和作品对后世产生了深远的影响。\n\n### 文学成就\n苏轼是中国文学史上的巨匠，其诗词、散文和书法作品广受赞誉。他的文学作品不仅展现了深刻的思想内涵和高超的艺术技巧，还对后世文学产生了深远的影响。苏轼在黄州期间创作的《赤壁赋》、《后赤壁赋》和《念奴娇·赤壁怀古》等作品，至今仍被视为中国文学史上的经典之作[Data: Reports (1); Entities (44, 46); Relationships (43, 44, 45)]。他的诗歌题材广泛，涵盖了社会现实、人生思考和自然景观，表现出深刻的思想内涵和高超的艺术技巧[Data: Entities (119); Relationships (123)]。此外，苏轼在词的创作上取得了突破性成就，打破了词为“艳科”的传统格局，提高了词的文学地位，使词从音乐的附属品转变为一种独立的抒情诗体[Data: Entities (116)]。\n\n### 政治生涯\n苏轼在北宋时期担任多个地方官职，关心百姓疾苦，致力于救灾和水利工程。他在徐州任职期间领导百姓抗洪救灾，保全了徐州城，展现了其卓越的领导能力和为民服务的精神[Data: Reports (1); Entities (20); Relationships (19, 24, 25)]。然而，因反对王安石变法，苏轼的仕途坎坷，多次调任地方官职。他曾因“乌台诗案”被贬为黄州团练副使，期间创作了大量脍炙人口的文学作品[Data: Reports (1); Entities (42); Relationships (43, 44, 45)]。\n\n### 与王安石的关系\n苏轼与王安石是北宋时期的两位著名政治家和文学家。王安石是新党的领袖，推行了一系列变法政策，而苏轼作为旧党的代表人物之一，与王安石在政见上产生了严重分歧。尽管两人在政治上存在对立，王安石曾上书为苏轼求情，显示出他对苏轼的尊重和对其才华的认可[Data: Reports (1); Entities (0, 15); Relationships (14)]。\n\n### 家族影响\n苏轼出生于名门，其父亲苏洵是古文名家，母亲程氏知书达理。苏洵在苏轼幼年时悉心传授学识与品行，对苏轼的成长和教育起到了重要作用。苏轼的弟弟苏辙也是北宋时期的文学家和政治家，兄弟二人在科举、仕途以及家庭责任方面有着紧密的联系和相互影响[Data: Reports (1); Entities (0, 2, 3); Relationships (0, 1, 2)]。\n\n### 师友情谊\n苏轼与欧阳修、梅尧臣等北宋时期的文学家和政治家有着深厚的师友情谊。欧阳修不仅是苏轼的师友，还极力称赞苏轼的才华，并推荐他参加制科考试。梅尧臣是苏轼科举考试的小试官，对苏轼的文章高度赏识。这些师友情谊对苏轼的文学成就和仕途发展起到了重要的推动作用[Data: Reports (1); Entities (0, 4, 5); Relationships (3, 4)]。\n\n### 总结\n苏轼是中国北宋时期的传奇人物，不仅在文学上成就斐然，还在政治上有诸多建树。他的生平和作品对后世产生了深远的影响，成为中国文学史上不可忽视的重要人物。尽管仕途坎坷，苏轼始终关心百姓疾苦，致力于救灾和水利工程，留下了许多脍炙人口的作品[Data: Reports (1); Entities (0); Relationships (0, 1, 2, 3, 4, +more)]。'

In [63]:
from IPython.display import Markdown, display

display(Markdown(result.response))

苏轼（1037-1101），字子瞻，号东坡居士，是中国北宋时期著名的文学家、政治家、书法家和诗人。他的一生充满了传奇色彩，不仅在文学上成就斐然，还在政治上有诸多建树，其生平和作品对后世产生了深远的影响。

### 文学成就
苏轼是中国文学史上的巨匠，其诗词、散文和书法作品广受赞誉。他的文学作品不仅展现了深刻的思想内涵和高超的艺术技巧，还对后世文学产生了深远的影响。苏轼在黄州期间创作的《赤壁赋》、《后赤壁赋》和《念奴娇·赤壁怀古》等作品，至今仍被视为中国文学史上的经典之作[Data: Reports (1); Entities (44, 46); Relationships (43, 44, 45)]。他的诗歌题材广泛，涵盖了社会现实、人生思考和自然景观，表现出深刻的思想内涵和高超的艺术技巧[Data: Entities (119); Relationships (123)]。此外，苏轼在词的创作上取得了突破性成就，打破了词为“艳科”的传统格局，提高了词的文学地位，使词从音乐的附属品转变为一种独立的抒情诗体[Data: Entities (116)]。

### 政治生涯
苏轼在北宋时期担任多个地方官职，关心百姓疾苦，致力于救灾和水利工程。他在徐州任职期间领导百姓抗洪救灾，保全了徐州城，展现了其卓越的领导能力和为民服务的精神[Data: Reports (1); Entities (20); Relationships (19, 24, 25)]。然而，因反对王安石变法，苏轼的仕途坎坷，多次调任地方官职。他曾因“乌台诗案”被贬为黄州团练副使，期间创作了大量脍炙人口的文学作品[Data: Reports (1); Entities (42); Relationships (43, 44, 45)]。

### 与王安石的关系
苏轼与王安石是北宋时期的两位著名政治家和文学家。王安石是新党的领袖，推行了一系列变法政策，而苏轼作为旧党的代表人物之一，与王安石在政见上产生了严重分歧。尽管两人在政治上存在对立，王安石曾上书为苏轼求情，显示出他对苏轼的尊重和对其才华的认可[Data: Reports (1); Entities (0, 15); Relationships (14)]。

### 家族影响
苏轼出生于名门，其父亲苏洵是古文名家，母亲程氏知书达理。苏洵在苏轼幼年时悉心传授学识与品行，对苏轼的成长和教育起到了重要作用。苏轼的弟弟苏辙也是北宋时期的文学家和政治家，兄弟二人在科举、仕途以及家庭责任方面有着紧密的联系和相互影响[Data: Reports (1); Entities (0, 2, 3); Relationships (0, 1, 2)]。

### 师友情谊
苏轼与欧阳修、梅尧臣等北宋时期的文学家和政治家有着深厚的师友情谊。欧阳修不仅是苏轼的师友，还极力称赞苏轼的才华，并推荐他参加制科考试。梅尧臣是苏轼科举考试的小试官，对苏轼的文章高度赏识。这些师友情谊对苏轼的文学成就和仕途发展起到了重要的推动作用[Data: Reports (1); Entities (0, 4, 5); Relationships (3, 4)]。

### 总结
苏轼是中国北宋时期的传奇人物，不仅在文学上成就斐然，还在政治上有诸多建树。他的生平和作品对后世产生了深远的影响，成为中国文学史上不可忽视的重要人物。尽管仕途坎坷，苏轼始终关心百姓疾苦，致力于救灾和水利工程，留下了许多脍炙人口的作品[Data: Reports (1); Entities (0); Relationships (0, 1, 2, 3, 4, +more)]。

In [64]:
result.context_data["reports"]

,id,title,content,rank,in_context
0,1,苏轼及其文学与政治影响,# 苏轼及其文学与政治影响\n\n本报告聚焦于北宋时期的文学家、政治家苏轼及其相关实体，包括...,8.5,True

In [65]:
result

SearchResult(response='苏轼（1037-1101），字子瞻，号东坡居士，是中国北宋时期著名的文学家、政治家、书法家和诗人。他的一生充满了传奇色彩，不仅在文学上成就斐然，还在政治上有诸多建树，其生平和作品对后世产生了深远的影响。\n\n### 文学成就\n苏轼是中国文学史上的巨匠，其诗词、散文和书法作品广受赞誉。他的文学作品不仅展现了深刻的思想内涵和高超的艺术技巧，还对后世文学产生了深远的影响。苏轼在黄州期间创作的《赤壁赋》、《后赤壁赋》和《念奴娇·赤壁怀古》等作品，至今仍被视为中国文学史上的经典之作[Data: Reports (1); Entities (44, 46); Relationships (43, 44, 45)]。他的诗歌题材广泛，涵盖了社会现实、人生思考和自然景观，表现出深刻的思想内涵和高超的艺术技巧[Data: Entities (119); Relationships (123)]。此外，苏轼在词的创作上取得了突破性成就，打破了词为“艳科”的传统格局，提高了词的文学地位，使词从音乐的附属品转变为一种独立的抒情诗体[Data: Entities (116)]。\n\n### 政治生涯\n苏轼在北宋时期担任多个地方官职，关心百姓疾苦，致力于救灾和水利工程。他在徐州任职期间领导百姓抗洪救灾，保全了徐州城，展现了其卓越的领导能力和为民服务的精神[Data: Reports (1); Entities (20); Relationships (19, 24, 25)]。然而，因反对王安石变法，苏轼的仕途坎坷，多次调任地方官职。他曾因“乌台诗案”被贬为黄州团练副使，期间创作了大量脍炙人口的文学作品[Data: Reports (1); Entities (42); Relationships (43, 44, 45)]。\n\n### 与王安石的关系\n苏轼与王安石是北宋时期的两位著名政治家和文学家。王安石是新党的领袖，推行了一系列变法政策，而苏轼作为旧党的代表人物之一，与王安石在政见上产生了严重分歧。尽管两人在政治上存在对立，王安石曾上书为苏轼求情，显示出他对苏轼的尊重和对其才华的认可[Data: Reports (1); Entities (0, 15); Relationships (14)]。\n\n### 家族影响\n苏轼出生于名门，其父亲苏洵是古文名家，母亲程氏知书达理。苏洵在苏轼幼年时悉心传授学识与品行，对苏轼的成长和教育起到了重要作用。苏轼的弟弟苏辙也是北宋时期的文学家和政治家，兄弟二人在科举、仕途以及家庭责任方面有着紧密的联系和相互影响[Data: Reports (1); Entities (0, 2, 3); Relationships (0, 1, 2)]。\n\n### 师友情谊\n苏轼与欧阳修、梅尧臣等北宋时期的文学家和政治家有着深厚的师友情谊。欧阳修不仅是苏轼的师友，还极力称赞苏轼的才华，并推荐他参加制科考试。梅尧臣是苏轼科举考试的小试官，对苏轼的文章高度赏识。这些师友情谊对苏轼的文学成就和仕途发展起到了重要的推动作用[Data: Reports (1); Entities (0, 4, 5); Relationships (3, 4)]。\n\n### 总结\n苏轼是中国北宋时期的传奇人物，不仅在文学上成就斐然，还在政治上有诸多建树。他的生平和作品对后世产生了深远的影响，成为中国文学史上不可忽视的重要人物。尽管仕途坎坷，苏轼始终关心百姓疾苦，致力于救灾和水利工程，留下了许多脍炙人口的作品[Data: Reports (1); Entities (0); Relationships (0, 1, 2, 3, 4, +more)]。', context_data={'reports':   id        title                                            content  rank  \
0  1  苏轼及其文学与政治影响  # 苏轼及其文学与政治影响\n\n本报告聚焦于北宋时期的文学家、政治家苏轼及其相关实体，包括...   8.5

   in_context
0        True  , 'relationships':       id source     target                                        description  \
0      0     苏轼         苏洵  苏轼是苏洵的儿子。苏洵在苏轼幼年时悉心传授学识与品行，对苏轼的成长和教育起到了重要作用。后来...
1      1     苏轼         程氏                         苏轼是程氏的儿子，程氏曾以东汉名士范滂的事迹激励苏轼
2      2     苏轼         苏辙  苏轼和苏辙是兄弟，他们一同随父亲苏洵赴京城参加科举考试，并在京城声名大噪。后来，因母亲病故，...
3      3     苏轼        欧阳修  苏轼和欧阳修是中国宋代著名的文学家和政治家。欧阳修不仅是苏轼的师友，还极力称赞苏轼的才华，并...
4      4     苏轼        梅尧臣                          梅尧臣是苏轼科举考试的小试官，对苏轼的文章高度赏识
..   ...    ...        ...                                                ...
116  119     苏轼  《和子由渑池怀旧》                    苏轼创作了《和子由渑池怀旧》，通过这首诗表达了对人生无常的感慨
117  120     苏轼          词                   苏轼在词的创作上取得了突破性成就，改革了词体，提高了词的文学地位
118  121     苏轼         庐山                     苏轼在《题西林壁》中描写了庐山，揭示了人们对事物认识的局限性
119  122     苏轼         渑池                     苏轼在《和子由渑池怀旧》中提到了渑池，表达了对人生无常的感慨
120  123     苏轼          诗             苏轼创作了大量诗歌，涵盖了社会现实、人生思考和自然景观，表现出深刻的思想内涵

    weight links  in_context
0     17.0     1        True
1      8.0     1        True
2     22.0     1        True
3     14.0     1        True
4      7.0     1        True
..     ...   ...         ...
116   14.0     1        True
117   10.0     1       False
118    6.0     1        True
119    6.0     1        True
120    8.0     1        True

[121 rows x 7 columns], 'entities':       id entity                                        description  \
0     89  皇家仪仗使                                     皇家仪仗使是李之纯担任的官职
1    100     哲宗                        哲宗是宋朝的皇帝，他在高太后去世后亲政，导致苏轼被贬。
2     75   元祐八年                                   元祐八年是苏轼出任定州知州的年份
3     93    海南岛                            海南岛是苏轼被贬至儋州的地方，位于中国最南端。
4     25     曹村  曹村是黄河决口的地点，这一事件在历史上具有重要意义。在苏轼担任徐州知州期间，黄河在曹村决口，...
..   ...    ...                                                ...
114   32    宋英宗
115    6   眉州眉山                           眉州眉山是苏轼的出生地，位于北宋时期的四川地区。
116   41     朝廷  朝廷是北宋时期的中央政府，负责管理国家事务并批准地方官员的提议。苏轼作为北宋时期的著名官员和...
117   77     扬州                                扬州是苏轼曾任职的地方，致力于改善民生
118   20     徐州  徐州是北宋著名文学家苏轼担任知州的地方。在苏轼任职期间，徐州遭遇了黄河决口的重大灾害。面对这...

    number of relationships  in_context
0                         1       False
1                         1       False
2                         1       False
3                         1       False
4                         1       False
..                      ...         ...
114                       1       False
115                       1       False
116                       1       False
117                       1        True
118                       1        True

[119 rows x 5 columns], 'sources':   id                                               text  in_context
0  0  # 苏轼：北宋文坛的璀璨巨星\n苏轼，这位北宋时期的传奇人物，于宋景祐三年十二月十九日（10...       False
1  1  ��步天下！”\n\n在欧阳修的极力称赞下，苏轼声名鹊起，一时间成为京城的焦点人物。他的每一...        True
2  2  1077年）四月至元丰二年（1079年）三月，苏轼在徐州任知州。期间，黄河在曹村决口，洪水泛...       False
3  3  山游览，触景生情，写下了《赤壁赋》《后赤壁赋》和《念奴娇·赤壁怀古》等千古名作，借景抒情，寄...        True
4  4  关注到杭州的水利问题。茅山有一条河专门容纳钱塘江潮水，盐桥有一条河专门容纳西湖水，但河道年久...        True
5  5  �年（1093年）九月，苏轼出任定州知州。然而，这一年高太后去世，哲宗开始亲政，新党再度掌权...        True
6  6  与哲思的交融\n苏轼的诗歌题材广泛，涵盖了社会现实、人生思考、自然景观等诸多方面。他对社会现...       False
7  7  现柔情之词扩展为表现豪情之词，将表现爱情之词扩展为表现性情之词，使词像诗一样可以充分展现作者...       False}, context_text='-----Reports-----\nid|title|content|rank\r\n1|苏轼及其文学与政治影响|"# 苏轼及其文学与政治影响\n\n本报告聚焦于北宋时期的文学家、政治家苏轼及其相关实体，包括其家族成员、师友、政治对手以及其文学创作的重要地点。苏轼不仅在文学上成就斐然，还在政治上有诸多建树，其生平和作品对后世产生了深远的影响。\n\n## 苏轼的文学成就\n\n苏轼是中国北宋时期的著名文学家，其诗词、散文和书法作品广受赞誉。他的文学作品不仅展现了深刻的思想内涵和高超的艺术技巧，还对后世文学产生了深远的影响。苏轼在黄州期间创作的《赤壁赋》、《后赤壁赋》和《念奴娇·赤壁怀古》等作品，至今仍被视为中国文学史上的经典之作。[Data: Entities (0); Relationships (43, 44, 45)]\n\n## 苏轼的政治生涯\n\n苏轼在北宋时期担任多个地方官职，关心百姓疾苦，致力于救灾和水利工程。然而，因反对王安石变法，苏轼的仕途坎坷，多次调任地方官职。尽管如此，他在徐州任职期间领导百姓抗洪救灾，保全了徐州城，展现了其卓越的领导能力和为民服务的精神。[Data: Entities (0, 20, 24, 25); Relationships (19, 24, 25)]\n\n## 苏轼与王安石的关系\n\n苏轼与王安石是北宋时期的两位著名政治家和文学家。王安石是新党的领袖，推行了一系列变法政策，而苏轼作为旧党的代表人物之一，与王安石在政见上产生了严重分歧。尽管两人在政治上存在对立，王安石曾上书为苏轼求情，显示出他对苏轼的尊重和对其才华的认可。[Data: Entities (0, 15); Relationships (14)]\n\n## 苏轼的家族影响\n\n苏轼出生于名门，其父亲苏洵是古文名家，母亲程氏知书达理。苏洵在苏轼幼年时悉心传授学识与品行，对苏轼的成长和教育起到了重要作用。苏轼的弟弟苏辙也是北宋时期的文学家和政治家，兄弟二人在科举、仕途以及家庭责任方面有着紧密的联系和相互影响。[Data: Entities (0, 2, 3); Relationships (0, 1, 2)]\n\n## 苏轼的师友情谊\n\n苏轼与欧阳修、梅尧臣等北宋时期的文学家和政治家有着深厚的师友情谊。欧阳修不仅是苏轼的师友，还极力称赞苏轼的才华，并推荐他参加制科考试。梅尧臣是苏轼科举考试的小试官，对苏轼的文章高度赏识。这些师友情谊对苏轼的文学成就和仕途发展起到了重要的推动作用。[Data: Entities (0, 4, 5); Relationships (3, 4)]"|8.5\r\n\n\n-----Entities-----\nid|entity|description|number of relationships\n0|苏轼|苏轼，字子瞻，号东坡居士，是中国北宋时期著名的文学家、政治家、书法家和诗人。他出生于眉州眉山（今四川眉山），出身名门，是初唐大臣苏味道的后裔。苏轼自幼在良好的家教环境中成长，父亲苏洵是古文名家，母亲程氏知书达理。他生性洒脱不羁，热爱交友、美食、品茗和游览山林。\n\n苏轼在嘉祐元年（1056年）首次离开四川，赴京城参加科举考试，其文章得到主考官欧阳修和小试官梅尧臣的高度赏识，声名鹊起。他以其诗词、散文和书法闻名，扩展了词的表现范围，使其能够展现作者的性情怀抱和人格个性。苏轼的文学成就极高，对后世影响深远，其诗歌涵盖了社会现实、人生思考和自然景观，表现出深刻的思想内涵和高超的艺术技巧。\n\n在政治上，苏轼历任多个官职，关心百姓疾苦，致力于救灾和水利工程。他曾在杭州、颍州、扬州、徐州和湖州等地任职，致力于改善民生和治理水利。然而，因反对王安石变法，苏轼的仕途坎坷，多次调任地方官职。他曾因“乌台诗案”被贬为黄州团练副使，期间创作了大量脍炙人口的文学作品，如《赤壁赋》和《念奴娇·赤壁怀古》等。\n\n苏轼的政治生涯中，曾担任定州知州，后被贬至惠州和儋州。在儋州期间，他办学堂传播文化，深受当地百姓爱戴。尽管仕途不顺，苏轼始终关心百姓疾苦，致力于救灾和水利工程，留下了许多脍炙人口的作品。\n\n总的来说，苏轼是中国北宋时期的传奇人物，不仅在文学上成就斐然，还在政治上有诸多建树。他的生平和作品对后世产生了深远的影响，成为中国文学史上不可忽视的重要人物。|117\n119|诗|苏轼的诗歌题材广泛，涵盖了社会现实、人生思考和自然景观，表现出深刻的思想内涵和高超的艺术技巧。|1\n4|欧阳修|欧阳修是北宋时期的著名文学家和政治家，与苏轼有着深厚的师友情谊。他曾担任苏轼科举考试的主考官，对苏轼的文章高度赏识，并预言其文章必独步天下。欧阳修极力称赞苏轼，并推荐他参加制科考试。然而，由于反对王安石变法，欧阳修后来被迫离开京城。尽管如此，他在文学和政治上的影响力依然深远，尤其是在对苏轼的提携和赏识方面，成为北宋文坛的重要人物之一。|1\n42|黄州团练副使|苏轼被贬为黄州团练副使，受到当地官员监视|1\n20|徐州|徐州是北宋著名文学家苏轼担任知州的地方。在苏轼任职期间，徐州遭遇了黄河决口的重大灾害。面对这一危机，苏轼展现出了卓越的领导能力，亲自带领百姓抗洪救灾。在他的指挥和努力下，徐州城得以保全，避免了更大的损失。这两段描述共同强调了苏轼在徐州任职期间的重要贡献，特别是他在抗洪救灾中的关键作用。|1\n18|杭州|杭州是苏轼第二次任职的地方，他在此担任通判，负责治理水利问题，包括河道疏浚、堤堰闸门修建以及西湖的治理。在此期间，苏轼不仅救灾治水，关心百姓疾苦，还领略了江南的美景，留下了许多脍炙人口的作品。杭州作为苏轼治理水利和文学创作的重要地点，见证了他对民生和自然的深刻关怀与贡献。|1\n65|中书舍人|中书舍人是苏轼在朝廷中的官职之一|1\n116|词|苏轼在词的创作上取得了突破性成就，打破了词为“艳科”的传统格局，提高了词的文学地位，使词从音乐的附属品转变为一种独立的抒情诗体。|1\n21|贤良方正能直言极谏科|贤良方正能直言极谏科是北宋时期的制科考试，苏轼在此考试中表现出色，被评为第三等，成为“百年第一”。|1\n46|念奴娇·赤壁怀古|《念奴娇·赤壁怀古》是北宋著名文学家苏轼在黄州期间创作的一首著名文学作品。这首作品以赤壁为背景，借景抒情，表达了苏轼对历史与人生的深刻思考。通过描绘赤壁的壮丽景色和历史典故，苏轼抒发了对英雄人物的缅怀以及对自身境遇的感慨。这首词不仅展现了苏轼卓越的文学才华，也成为了中国古典文学中的经典之作。|1\n67|知制诰|知制诰是苏轼在朝廷中的官职之一|1\n1|苏洵|苏洵是北宋时期的文学家、政治家和古文名家，学识渊博。他是著名文学家苏轼和苏辙的父亲，在苏轼幼年时悉心传授学识与品行，对两位儿子的成长和教育产生了深远影响。苏洵曾在京城担任试秘书省校书郎，后因病逝世。他去世后，苏轼和苏辙回乡守孝，以尽孝道。苏洵不仅在文学上成就斐然，还以其深厚的学识和高尚的品行在北宋文坛和政治领域留下了重要印记。|2\n47|东坡居士|苏轼在黄州期间自号“东坡居士”|1\n77|扬州|扬州是苏轼曾任职的地方，致力于改善民生|1\n104|舒州|舒州是苏轼被调为团练副使的地方。|1\n84|侍读|侍读是苏轼兼任的官职|1\n33|湖州|湖州是苏轼调任知州的地方，因“乌台诗案”在此被捕|1\n44|赤壁赋|《赤壁赋》是苏轼在黄州期间创作的著名文学作品。这篇作品以赤壁为背景，借景抒情，表达了作者对自然美景的赞美以及对人生哲理的深刻思考。苏轼通过描绘赤壁的壮丽景色，抒发了自己的情感和思想，展现了其卓越的文学才华和深厚的艺术造诣。《赤壁赋》不仅是中国文学史上的经典之作，也是苏轼个人创作生涯中的重要代表作之一。|1\n63|礼部郎中|礼部郎中是苏轼在朝廷中的官职之一|1\n68|知礼部贡举|知礼部贡举是苏轼在朝廷中的官职之一|1\n\n\n-----Relationships-----\nid|source|target|description|weight|links\n123|苏轼|诗|苏轼创作了大量诗歌，涵盖了社会现实、人生思考和自然景观，表现出深刻的思想内涵|8.0|1\n0|苏轼|苏洵|苏轼是苏洵的儿子。苏洵在苏轼幼年时悉心传授学识与品行，对苏轼的成长和教育起到了重要作用。后来，苏洵因病逝世，苏轼回乡守孝，以表达对父亲的哀悼与敬意。这两段描述共同展现了苏轼与苏洵之间深厚的父子关系，以及苏洵对苏轼在学识、品行和情感上的深远影响。|17.0|1\n15|苏轼|谢景温|谢景温受王安石指使在宋神宗面前诋毁苏轼，导致苏轼请求出京任职|5.0|1\n59|苏轼|茅山|苏轼组织人力疏浚茅山河道|7.0|1\n60|苏轼|盐桥|苏轼组织人力疏浚盐桥河道|7.0|1\n118|苏轼|《题西林壁》|苏轼创作了《题西林壁》，通过这首诗表达了对事物认识的局限性|14.0|1\n119|苏轼|《和子由渑池怀旧》|苏轼创作了《和子由渑池怀旧》，通过这首诗表达了对人生无常的感慨|14.0|1\n121|苏轼|庐山|苏轼在《题西林壁》中描写了庐山，揭示了人们对事物认识的局限性|6.0|1\n122|苏轼|渑池|苏轼在《和子由渑池怀旧》中提到了渑池，表达了对人生无常的感慨|6.0|1\n70|茅山|苏轼|苏轼组织人力疏浚茅山的河道|7.0|1\n71|盐桥|苏轼|苏轼组织人力疏浚盐桥的河道|7.0|1\n72|钱塘江|苏轼|苏轼修建堤堰闸门，防止钱塘江潮水涌入杭州城内|8.0|1\n73|西湖|苏轼|苏轼疏浚西湖并修筑苏公堤|9.0|1\n1|苏轼|程氏|苏轼是程氏的儿子，程氏曾以东汉名士范滂的事迹激励苏轼|8.0|1\n2|苏轼|苏辙|苏轼和苏辙是兄弟，他们一同随父亲苏洵赴京城参加科举考试，并在京城声名大噪。后来，因母亲病故，兄弟二人回乡守丧。守丧期满后，他们重返京城并担任官职。苏轼因苏辙担任尚书右丞而改任翰林承旨。这段描述展现了苏轼和苏辙兄弟二人在科举、仕途以及家庭责任方面的紧密联系和相互影响。|22.0|1\n3|苏轼|欧阳修|苏轼和欧阳修是中国宋代著名的文学家和政治家。欧阳修不仅是苏轼的师友，还极力称赞苏轼的才华，并推荐他参加制科考试。此外，欧阳修还曾担任苏轼科举考试的主考官，对苏轼的文章高度赏识。两人的关系既是师生，也是朋友，欧阳修对苏轼的文学成就和仕途发展起到了重要的推动作用。|14.0|1\n4|苏轼|梅尧臣|梅尧臣是苏轼科举考试的小试官，对苏轼的文章高度赏识|7.0|1\n5|苏轼|眉州眉山|苏轼出生于眉州眉山|9.0|1\n6|苏轼|京城|苏轼曾赴京城参加科举考试并声名鹊起|8.0|1\n7|苏轼|科举考试|苏轼在嘉祐元年（1056年）参加科举考试并取得优异成绩|1.0|1\n8|苏轼|苏味道|苏轼是苏味道的后裔|7.0|1\n\n\n-----Sources-----\nid|text\n4|关注到杭州的水利问题。茅山有一条河专门容纳钱塘江潮水，盐桥有一条河专门容纳西湖水，但河道年久失修，影响通航。苏轼于是组织人力疏浚这两条河道，又修造堤堰闸门，控制西湖水的蓄积与排泄，使钱塘江潮水不再涌入杭州城内。他还利用剩余的人力修复了六井，将挖出来的淤泥堆积在西湖中，修筑成一条长达三十里的长堤，方便行人往来。吴地百姓有种菱的习惯，春天会除草，不留寸草。苏轼便雇募人力在西湖中种菱，既防止了水草生长，又将种菱的收入作为日后修浚西湖的费用。他还动用救济荒灾剩余的一万缗钱、万石粮食，以及申请得到的一百张僧人度牒，用于雇募民工。长堤建成后，苏轼在堤上种植芙蓉、杨柳，放眼望去，如同一幅美丽的画卷，杭州人将其命名为苏公堤。苏公堤不仅是一项水利工程，更是苏轼留给杭州百姓的宝贵财富，成为了杭州的一道亮丽风景线。\n\n苏轼在杭州的日子过得惬意自在，他自比唐代的白居易，为百姓做了许多实事，深受百姓爱戴。然而，元祐六年（1091年），他又被召回朝廷，拟任吏部尚书。但由于弟弟苏辙担任尚书右丞，为了避嫌，苏轼改任翰林承旨。不久，在八月，苏轼又因政见不合，请求出任地方官，以龙图阁学士的身份出知颍州。\n\n元祐七年（1092年）二月，苏轼调任扬州知州。在扬州，他同样心系百姓，致力于改善民生。然而，没过一年，朝廷又以兵部尚书的职务将他召回京城，兼任侍读。这一年，宋哲宗到南郊祭祀，苏轼担任卤簿使，负责导驾进入太庙。祭祀途中，有赭伞犊车并青盖犊车十余辆与皇帝的仪仗争道，毫不避让。苏轼见状，立即派御营巡检使前去调查，得知是皇后及大长公主的车队。当时，御史中丞李之纯担任皇家仪仗使，苏轼要求他上奏皇帝，但李之纯畏惧皇后与大长公主的权势，不敢上奏。苏轼于是在车中直接向哲宗上奏此事，哲宗将奏书派人送给太皇太后处理。第二天，朝廷便下诏书整肃仪仗队伍，规定从皇后而下都不许迎接谒见。不久后，苏轼担任礼部尚书，兼端明殿学士、翰林侍读学士。\n\n元祐八年（1093年）九月，苏轼出任定州知州。然而，这一年高太后去世，哲宗开始亲政，新党再度掌权。苏轼的命运也随之急转直下，他再次成为被打击的对象。\n\n绍圣元年（1094年）六月，苏\n3|山游览，触景生情，写下了《赤壁赋》《后赤壁赋》和《念奴娇·赤壁怀古》等千古名作，借景抒情，寄托自己谪居时的复杂情感。\n\n元丰七年（1084年），苏轼离开黄州，奉诏前往汝州就任。长途跋涉，旅途劳顿，苏轼的幼儿不幸夭折。汝州路途遥远，且路费已尽，再加上丧子之痛，苏轼上书朝廷，请求暂时前往常州居住，得到了朝廷的批准。常州水网交错，风景秀丽，苏轼在这里感受到了久违的宁静与舒适。他本打算在此终老，然而命运再次发生转折。\n\n元丰八年（1085年），宋哲宗即位，高太后临朝听政，司马光重新被启用为相，以王安石为首的新党遭到打压。苏轼迎来了人生的又一次转机，他被重新任命为朝奉郎知登州（蓬莱）。四个月后，苏轼以礼部郎中的身份被召回朝廷。在朝廷的短短半个月，他就升任起居舍人。三个月后，又晋升为中书舍人。不久，苏轼再被提拔为翰林学士、知制诰，知礼部贡举，可谓平步青云。\n\n然而，苏轼并没有被官场的得意冲昏头脑。当他看到新兴势力拼命压制王安石集团的人物，并且尽废新法后，他认为这些人与所谓的“王党”并无本质区别，于是再次向朝廷提出谏议。苏轼对旧党执政后暴露出的腐败现象进行了严厉抨击，这也让他再次引起了保守势力的强烈反对，遭到诬告陷害。此时的苏轼，既无法被新党接纳，又不能得到旧党的谅解，无奈之下，他再度自求外调。\n\n## 心系百姓，造福一方\n元祐四年（1089年），苏轼出任龙图阁学士、知杭州。这是他第二次到杭州任职，此时的杭州正面临着大旱，饥馑与瘟疫同时肆虐。苏轼心急如焚，立即向朝廷请求减免本路上供米的三分之一，又得到朝廷赐给的剃度和尚的度牒，换成大米来救济饥饿的百姓。元祐五年（1090年）春天，苏轼又减价出售常平米，还熬制了大量的厚粥和汤药，派人带着医生分街坊为百姓治病，救活了无数人。苏轼深知杭州作为水陆交会之地，瘟疫导致的死亡人数往往比其他地方更多。于是，他拿出公款二千缗，又自掏黄金五十两，创办病坊，储备钱粮，收治患病的百姓。\n\n苏轼还关注到杭州的水利问题。茅山有一条河专门容纳钱塘江潮水，盐桥有一条河专门容纳西湖水，但河道年久失修，影响通航。苏轼于是组织人力疏浚这两条河道，又修造堤�\n5|�年（1093年）九月，苏轼出任定州知州。然而，这一年高太后去世，哲宗开始亲政，新党再度掌权。苏轼的命运也随之急转直下，他再次成为被打击的对象。\n\n绍圣元年（1094年）六月，苏轼被贬为宁远军节度副使，再次被贬至惠州（今广东惠州）。绍圣四年（1097年），苏轼的人生陷入了更深的困境，他被一叶孤舟送到了荒僻的海南岛儋州。在宋朝，放逐海南是仅次于满门抄斩的严厉处罚。但苏轼并没有被困境打倒，他把儋州当成了自己的第二故乡，在这里办学堂，传播文化，培养学风。许多人不远千里，追随苏轼求学。在苏轼之前的宋代一百多年里，海南从未有人进士及第。但苏轼北归不久，海南的姜唐佐就考中了乡贡。苏轼为此题诗：“沧海何曾断地脉，珠崖从此破天荒。”苏轼以自己的学识和人格魅力，成为了儋州文化的开拓者和播种人，深受当地百姓的崇敬和爱戴。在儋州，留下了许多与苏轼有关的遗迹，如东坡村、东坡井、东坡田、东坡路、东坡桥、东坡帽等，这些遗迹见证了苏轼在儋州的生活，也表达了人们对他的缅怀之情。\n\n## 北归途中，巨星陨落\n宋徽宗即位后，苏轼的命运终于出现了一丝转机。他相继被调为廉州安置、舒州团练副使、永州安置。元符三年四月（1100年），朝廷颁行大赦，苏轼复任朝奉郎。苏轼踏上了北归的路途，他的心中充满了对故乡和亲人的思念。然而，命运却没有给他太多的时间。建中靖国元年七月二十八日（1101年8月24日），苏轼在常州（今属江苏）永远地闭上了眼睛。苏轼在临终前留下遗嘱，希望葬在汝州郏城县（今河南郏县）钧台乡上瑞里。次年，他的儿子苏过遵照遗嘱，将父亲的灵柩运至郏城县安葬。苏轼的一生，充满了坎坷与传奇，他的离去，让无数人为之悲痛。\n\n宋高宗即位后，追赠苏轼为太师；宋孝宗时，追谥“文忠”。苏轼虽然离开了人世，但他的文学成就和人格魅力却永远地留在了人们的心中。\n\n## 文学成就，光照千秋\n苏轼在文学领域的成就堪称登峰造极，他的诗作、词作和文章都达到了极高的水准，对后世文学的发展产生了深远的影响。\n\n### 诗作：批判与哲思的交融\n苏轼的诗歌题材广泛，涵盖了社会现实、人生思考、自然景观等诸多方面。他对社会现实有着深刻的洞察和批判精神，在二千七百多首苏诗中，干预社\n1|��步天下！”\n\n在欧阳修的极力称赞下，苏轼声名鹊起，一时间成为京城的焦点人物。他的每一篇新作，都如同春风拂过大地，迅速传遍京城的大街小巷。正当苏轼父子在京城声名大噪，准备大展宏图之时，命运却给他们泼了一盆冷水，苏轼、苏辙的母亲突然病故。悲痛万分的兄弟二人只能随父亲回乡奔丧，暂时告别了京城的繁华。\n\n嘉祐四年（1059年）十月，守丧期满。次年二月，三苏再次踏上前往汴京的道路。回到京城后，苏轼被授予河南府福昌县主簿一职，苏洵则任试秘书省校书郎。嘉祐六年（1061年），在欧阳修的推荐下，苏轼兄弟参加了“贤良方正能直言极谏科”的制科考试。苏轼凭借出色的表现，对策被评为第三等（一、二等虚设，第三等为实际上第一等）。此前宋朝只有吴育中过此等制科的第三等，苏轼的成功堪称“百年第一”。随后，他被授予大理评事、签书凤翔府判官。四年后，苏轼还朝，任判登闻鼓院，又顺利通过学士院的考试，担任直史馆。\n\n然而，命运似乎总爱捉弄苏轼。宋英宗治平三年（1066年），苏洵病逝，苏轼、苏辙兄弟再次扶柩还乡，守孝三年。三年后，苏轼重返朝廷，此时，王安石变法正如火如荼地展开。苏轼的许多师友，包括欧阳修在内，都因反对新法而与王安石政见不合，纷纷被迫离京。曾经热闹的朝堂如今变得冷冷清清，苏轼眼中的世界也不再是二十岁时那个平和美好的模样，他的内心充满了忧虑与无奈。\n\n## 仕途坎坷，漂泊四方\n宋神宗熙宁四年（1071年），苏轼怀着对国家和百姓的责任感，上书直言新法的弊病。这一举动触怒了王安石，王安石指使御史谢景温在神宗面前诋毁苏轼。苏轼深知朝堂斗争的复杂，为了远离纷争，他主动请求出京任职，最终被任命为杭州通判。在杭州，苏轼尽情领略江南的美景，与友人游山玩水，饮酒赋诗，留下了许多脍炙人口的佳作。\n\n熙宁七年（1074年）秋天，苏轼又调任密州（今山东诸城）知州。在密州，他虽然生活条件艰苦，但依然心系百姓。在这里，他写下了《江城子·密州出猎》等豪迈之作，展现出他的雄心壮志和爱国情怀。熙宁十年（1077年）四月至元丰二年（1079年）三月，苏轼在徐州任知州。期间，黄河在曹村决口，洪水泛滥，徐州城危在旦夕。苏轼挺身而出，身先士卒，带领百姓抗洪救�\n', completion_time=47.18458580970764, llm_calls=1, prompt_tokens=10721, output_tokens=1470, llm_calls_categories={'build_context': 0, 'response': 1}, prompt_tokens_categories={'build_context': 0, 'response': 10721}, output_tokens_categories={'build_context': 0, 'response': 1470})

## 2、global查询

In [66]:
import pandas as pd
import tiktoken

from graphrag.query.indexer_adapters import (
    read_indexer_communities,
    read_indexer_entities,
    read_indexer_reports,
)
from graphrag.query.llm.oai.chat_openai import ChatOpenAI
from graphrag.query.llm.oai.typing import OpenaiApiType
from graphrag.query.structured_search.global_search.community_context import (
    GlobalCommunityContext,
)
from graphrag.query.structured_search.global_search.search import GlobalSearch

In [67]:
community_df = pd.read_parquet("./sushi/output/create_final_communities.parquet")
communities = read_indexer_communities(community_df, nodes_df, report_df)

In [68]:
context_builder = GlobalCommunityContext(
    community_reports=reports,
    communities=communities,
    entities=entities,  
    token_encoder=token_encoder,
)

In [69]:
context_builder_params = {
    "use_community_summary": False,  
    "shuffle_data": True,
    "include_community_rank": True,
    "min_community_rank": 0,
    "community_rank_name": "rank",
    "include_community_weight": True,
    "community_weight_name": "occurrence weight",
    "normalize_community_weight": True,
    "max_tokens": 12_000,  
    "context_name": "Reports",
}

map_llm_params = {
    "max_tokens": 1000,
    "temperature": 0.0,
    "response_format": {"type": "json_object"},
}

reduce_llm_params = {
    "max_tokens": 2000, 
    "temperature": 0.0,
}

In [70]:
search_engine = GlobalSearch(
    llm=llm,
    context_builder=context_builder,
    token_encoder=token_encoder,
    max_data_tokens=12_000,  
    map_llm_params=map_llm_params,
    reduce_llm_params=reduce_llm_params,
    allow_general_knowledge=False, 
    json_mode=True,  
    context_builder_params=context_builder_params,
    concurrent_coroutines=32,
    response_type="multiple paragraphs",
)

In [75]:
result = await search_engine.asearch("评价下苏轼")

In [76]:
display(Markdown(result.response))

苏轼是中国北宋时期的一位杰出文学家、政治家和书法家，其成就和影响在中国历史上具有重要地位。以下从文学成就、政治贡献、家庭背景以及人际关系等方面对其作出评价。

### 文学成就
苏轼的文学作品，尤其是诗词和散文，展现了他深刻的思想内涵和高超的艺术技巧。他在黄州期间创作的《赤壁赋》、《后赤壁赋》和《念奴娇·赤壁怀古》等作品，至今仍被视为中国文学史上的经典之作。这些作品不仅在当时广受赞誉，还对后世文学产生了深远的影响 [Data: Reports (1)]。

### 政治贡献
苏轼在北宋时期担任多个地方官职，关心百姓疾苦，致力于救灾和水利工程。他在徐州任职期间领导百姓抗洪救灾，保全了徐州城，展现了其卓越的领导能力和为民服务的精神。这种为民请命的精神和实际行动，使他在政治上赢得了广泛的尊重 [Data: Reports (1)]。

### 家庭背景
苏轼出生于名门，其父亲苏洵是古文名家，母亲程氏知书达理。苏洵在苏轼幼年时悉心传授学识与品行，对苏轼的成长和教育起到了重要作用。苏轼的弟弟苏辙也是北宋时期的文学家和政治家，兄弟二人在科举、仕途以及家庭责任方面有着紧密的联系和相互影响 [Data: Reports (1, 5)]。

### 人际关系
苏轼与欧阳修、梅尧臣等北宋时期的文学家和政治家有着深厚的师友情谊。欧阳修不仅是苏轼的师友，还极力称赞苏轼的才华，并推荐他参加制科考试。梅尧臣是苏轼科举考试的小试官，对苏轼的文章高度赏识。这些师友情谊对苏轼的文学成就和仕途发展起到了重要的推动作用 [Data: Reports (1)]。

### 与王安石的关系
尽管苏轼与王安石在政治上存在对立，王安石曾上书为苏轼求情，显示出他对苏轼的尊重和对其才华的认可。这种复杂的关系反映了北宋时期政治和文化的多元性 [Data: Reports (1)]。

综上所述，苏轼不仅在文学上取得了卓越的成就，还在政治、家庭和人际关系等方面展现了其多方面的才华和影响力。他的作品和精神至今仍对中国文化产生深远的影响。

In [77]:
result

GlobalSearchResult(response='苏轼是中国北宋时期的一位杰出文学家、政治家和书法家，其成就和影响在中国历史上具有重要地位。以下从文学成就、政治贡献、家庭背景以及人际关系等方面对其作出评价。\n\n### 文学成就\n苏轼的文学作品，尤其是诗词和散文，展现了他深刻的思想内涵和高超的艺术技巧。他在黄州期间创作的《赤壁赋》、《后赤壁赋》和《念奴娇·赤壁怀古》等作品，至今仍被视为中国文学史上的经典之作。这些作品不仅在当时广受赞誉，还对后世文学产生了深远的影响 [Data: Reports (1)]。\n\n### 政治贡献\n苏轼在北宋时期担任多个地方官职，关心百姓疾苦，致力于救灾和水利工程。他在徐州任职期间领导百姓抗洪救灾，保全了徐州城，展现了其卓越的领导能力和为民服务的精神。这种为民请命的精神和实际行动，使他在政治上赢得了广泛的尊重 [Data: Reports (1)]。\n\n### 家庭背景\n苏轼出生于名门，其父亲苏洵是古文名家，母亲程氏知书达理。苏洵在苏轼幼年时悉心传授学识与品行，对苏轼的成长和教育起到了重要作用。苏轼的弟弟苏辙也是北宋时期的文学家和政治家，兄弟二人在科举、仕途以及家庭责任方面有着紧密的联系和相互影响 [Data: Reports (1, 5)]。\n\n### 人际关系\n苏轼与欧阳修、梅尧臣等北宋时期的文学家和政治家有着深厚的师友情谊。欧阳修不仅是苏轼的师友，还极力称赞苏轼的才华，并推荐他参加制科考试。梅尧臣是苏轼科举考试的小试官，对苏轼的文章高度赏识。这些师友情谊对苏轼的文学成就和仕途发展起到了重要的推动作用 [Data: Reports (1)]。\n\n### 与王安石的关系\n尽管苏轼与王安石在政治上存在对立，王安石曾上书为苏轼求情，显示出他对苏轼的尊重和对其才华的认可。这种复杂的关系反映了北宋时期政治和文化的多元性 [Data: Reports (1)]。\n\n综上所述，苏轼不仅在文学上取得了卓越的成就，还在政治、家庭和人际关系等方面展现了其多方面的才华和影响力。他的作品和精神至今仍对中国文化产生深远的影响。', context_data={'reports':   id                 title  occurrence weight  \
0  1           苏轼及其文学与政治影响              1.000
1  5                苏洵与秘书省              0.250
2  4  West Lake and Su Shi              0.250
3  6                茅山与钱塘江              0.250
4  3              谢景温与北宋御史              0.125
5  2             庐山与《题西林壁》              0.125
6  0              苏轼与渑池的哲思              0.125

                                             content  rank
0  # 苏轼及其文学与政治影响\n\n本报告聚焦于北宋时期的文学家、政治家苏轼及其相关实体，包括...   8.5
1  # 苏洵与秘书省\n\n该社区围绕苏洵和秘书省两个关键实体展开。苏洵是北宋时期的文学家、政治...   7.5
2  # West Lake and Su Shi\n\nThe community center...   7.5
3  # 茅山与钱塘江\n\n该社区围绕茅山和钱塘江展开，钱塘江是杭州附近的一条主要河流，以其壮观...   6.5
4  # 谢景温与北宋御史\n\n该社区围绕谢景温与北宋御史的关系展开。谢景温是北宋时期的御史，受...   7.5
5  # 庐山与《题西林壁》\n\n该社区围绕庐山和苏轼的诗《题西林壁》展开，庐山作为自然景观在诗...   3.5

In [78]:
result.context_data["reports"]

,id,title,occurrence weight,content,rank
0,1,苏轼及其文学与政治影响,1.000,# 苏轼及其文学与政治影响\n\n本报告聚焦于北宋时期的文学家、政治家苏轼及其相关实体，包括...,8.5
1,5,苏洵与秘书省,0.250,# 苏洵与秘书省\n\n该社区围绕苏洵和秘书省两个关键实体展开。苏洵是北宋时期的文学家、政治...,7.5
2,4,West Lake and Su Shi,0.250,# West Lake and Su Shi\n\nThe community center...,7.5
3,6,茅山与钱塘江,0.250,# 茅山与钱塘江\n\n该社区围绕茅山和钱塘江展开，钱塘江是杭州附近的一条主要河流，以其壮观...,6.5
4,3,谢景温与北宋御史,0.125,# 谢景温与北宋御史\n\n该社区围绕谢景温与北宋御史的关系展开。谢景温是北宋时期的御史，受...,7.5
5,2,庐山与《题西林壁》,0.125,# 庐山与《题西林壁》\n\n该社区围绕庐山和苏轼的诗《题西林壁》展开，庐山作为自然景观在诗...,3.5
6,0,苏轼与渑池的哲思,0.125,# 苏轼与渑池的哲思\n\n该社区围绕苏轼及其诗作《和子由渑池怀旧》展开，渑池作为诗中的地点...,3.5

## 3、可视化

In [79]:
from py2neo import Graph, Node, Relationship, Subgraph, NodeMatcher

### 3.1 连接neo4j

In [98]:
# 连接到 Neo4j 数据库
Neo4jgraph = Graph("bolt://localhost:7687", auth=("neo4j", "1qa2ws#ED"))

# 清除现有数据（可选，根据需要）
Neo4jgraph.delete_all()

In [99]:
GRAPHRAG_FOLDER="xiyou/output/"

In [100]:
import pandas as pd
from neo4j import GraphDatabase
import time

In [101]:
NEO4J_URI="bolt://localhost:7687"
NEO4J_USERNAME="neo4j"
NEO4J_PASSWORD="1qa2ws#ED"
NEO4J_DATABASE="neo4j"

driver = GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USERNAME, NEO4J_PASSWORD))

分批导入

In [102]:
def batched_import(statement, df, batch_size=1000):
    """
    Import a dataframe into Neo4j using a batched approach.
    Parameters: statement is the Cypher query to execute, df is the dataframe to import, and batch_size is the number of rows to import in each batch.
    """
    total = len(df)
    start_s = time.time()
    for start in range(0,total, batch_size):
        batch = df.iloc[start: min(start+batch_size,total)]
        result = driver.execute_query("UNWIND $rows AS value " + statement, 
                                      rows=batch.to_dict('records'),
                                      database_=NEO4J_DATABASE)
        print(result.summary.counters)
    print(f'{total} rows in { time.time() - start_s} s.')    
    return total

创建唯一约束的 Cypher 查询语句

In [103]:
# create constraints, idempotent operation

statements = """
create constraint chunk_id if not exists for (c:__Chunk__) require c.id is unique;
create constraint document_id if not exists for (d:__Document__) require d.id is unique;
create constraint entity_id if not exists for (c:__Community__) require c.community is unique;
create constraint entity_id if not exists for (e:__Entity__) require e.id is unique;
create constraint entity_title if not exists for (e:__Entity__) require e.human_readable_id is unique;
create constraint entity_title if not exists for (e:__Covariate__) require e.title is unique;
create constraint related_id if not exists for ()-[rel:RELATED]->() require rel.id is unique;
""".split(";")

for statement in statements:
    if len((statement or "").strip()) > 0:
        print(statement)
        driver.execute_query(statement)

create constraint chunk_id if not exists for (c:__Chunk__) require c.id is unique

create constraint document_id if not exists for (d:__Document__) require d.id is unique

create constraint entity_id if not exists for (c:__Community__) require c.community is unique

create constraint entity_id if not exists for (e:__Entity__) require e.id is unique

create constraint entity_title if not exists for (e:__Entity__) require e.human_readable_id is unique

create constraint entity_title if not exists for (e:__Covariate__) require e.title is unique

create constraint related_id if not exists for ()-[rel:RELATED]->() require rel.id is unique

### 3.2 导入

Documents

In [104]:
doc_df = pd.read_parquet(f'{GRAPHRAG_FOLDER}/create_final_documents.parquet', columns=["id", "title"])
doc_df.head(2)

                                                  id    title
0  f0353530ee9676e3ee4e365a2a68f984bbc678f1c51fe7...  西游记.txt

In [105]:
# import documents
statement = """
MERGE (d:__Document__ {id:value.id})
SET d += value {.title}
"""

batched_import(statement, doc_df)

{'_contains_updates': True, 'labels_added': 1, 'nodes_created': 1, 'properties_set': 2}
1 rows in 0.07112288475036621 s.

1

text_units

In [106]:
text_df = pd.read_parquet(f'{GRAPHRAG_FOLDER}/create_final_text_units.parquet',
                          columns=["id","text","n_tokens","document_ids"])
text_df.head(2)

,id,text,n_tokens,document_ids
0,40fdd9a0bfa663c69650d94b7dea8c99955653ba6f58f9...,﻿\n\n\n《》目录 第一回 灵根育孕源流出 心性修持大道生\n\n<br /><br /...,1200,[f0353530ee9676e3ee4e365a2a68f984bbc678f1c51fe...
1,8d356ee8dae43851867c9d5a74a5259b9eae967dbb126c...,东海之处耸崇巅。丹崖怪石，削壁奇峰。丹崖上，彩凤双鸣；削壁前，麒麟独卧。峰头时听锦鸡鸣，石窟...,1200,[f0353530ee9676e3ee4e365a2a68f984bbc678f1c51fe...

In [107]:
statement = """
MERGE (c:__Chunk__ {id:value.id})
SET c += value {.text, .n_tokens}
WITH c, value
UNWIND value.document_ids AS document
MATCH (d:__Document__ {id:document})
MERGE (c)-[:PART_OF]->(d)
"""

batched_import(statement, text_df)

{'_contains_updates': True, 'labels_added': 897, 'relationships_created': 897, 'nodes_created': 897, 'properties_set': 2691}
897 rows in 1.3100485801696777 s.

897

entities

In [108]:
entity_df = pd.read_parquet(f'{GRAPHRAG_FOLDER}/create_final_entities.parquet',
                            columns=["id","type","description","human_readable_id","title","text_unit_ids"])
entity_df.head(2)

,id,type,description,human_readable_id,title,text_unit_ids
0,6fc43c7c-5d40-4b5b-9dfd-3135f8c88690,PERSON,Pan Gu is a mythical figure who is credited wi...,0,PAN GU,[40fdd9a0bfa663c69650d94b7dea8c99955653ba6f58f...
1,4ea9cb76-610d-4216-b160-ec8547ce1999,GEO,The Eastern Supreme Divine Continent is one of...,1,EASTERN SUPREME DIVINE CONTINENT,[40fdd9a0bfa663c69650d94b7dea8c99955653ba6f58f...

In [109]:
entity_statement = """
MERGE (e:__Entity__ {id:value.id})
SET e += value {.human_readable_id, .description, title:replace(value.title,'"','')}
WITH e, value
CALL apoc.create.addLabels(e, case when coalesce(value.type,"") = "" then [] else [apoc.text.upperCamelCase(replace(value.type,'"',''))] end) yield node
UNWIND value.text_unit_ids AS text_unit
MATCH (c:__Chunk__ {id:text_unit})
MERGE (c)-[:HAS_ENTITY]->(e)
"""

batched_import(entity_statement, entity_df)

{'_contains_updates': True, 'labels_added': 1000, 'relationships_created': 3806, 'nodes_created': 1000, 'properties_set': 4000}
{'_contains_updates': True, 'labels_added': 1000, 'relationships_created': 1414, 'nodes_created': 1000, 'properties_set': 4000}
{'_contains_updates': True, 'labels_added': 897, 'relationships_created': 1223, 'nodes_created': 897, 'properties_set': 3588}
2897 rows in 6.9274938106536865 s.

2897

relationships

In [110]:
rel_df = pd.read_parquet(f'{GRAPHRAG_FOLDER}/create_final_relationships.parquet',
                         columns=["source","target","id","weight","human_readable_id","description","text_unit_ids"])
rel_df.head(2)

,source,target,id,weight,human_readable_id,description,text_unit_ids
0,PAN GU,EASTERN SUPREME DIVINE CONTINENT,e27439ab-bc44-49bc-a185-22eea6fe022f,5.0,0,Pan Gu is associated with the creation of the ...,[40fdd9a0bfa663c69650d94b7dea8c99955653ba6f58f...
1,PAN GU,WESTERN OX-HERD CONTINENT,771c29eb-7d86-4ddf-8986-1297a5f4ac97,5.0,1,Pan Gu is associated with the creation of the ...,[40fdd9a0bfa663c69650d94b7dea8c99955653ba6f58f...

In [111]:
rel_statement = """
    MATCH (source:__Entity__ {title:replace(value.source,'"','')})
    MATCH (target:__Entity__ {title:replace(value.target,'"','')})
    // not necessary to merge on id as there is only one relationship per pair
    MERGE (source)-[rel:RELATED {id: value.id}]->(target)
    SET rel += value {.rank, .weight, .human_readable_id, .description, .text_unit_ids}
    RETURN count(*) as createdRels
"""

batched_import(rel_statement, rel_df)

{'_contains_updates': True, 'relationships_created': 1000, 'properties_set': 6000}
{'_contains_updates': True, 'relationships_created': 1000, 'properties_set': 6000}
{'_contains_updates': True, 'relationships_created': 1000, 'properties_set': 6000}
{'_contains_updates': True, 'relationships_created': 1000, 'properties_set': 6000}
{'_contains_updates': True, 'relationships_created': 1000, 'properties_set': 6000}
{'_contains_updates': True, 'relationships_created': 382, 'properties_set': 2292}
5382 rows in 31.70318055152893 s.

5382

communities

In [112]:
community_df = pd.read_parquet(f'{GRAPHRAG_FOLDER}/create_final_communities.parquet', 
                     columns=["id","level","title","text_unit_ids","relationship_ids"])

community_df.head(2)

,id,level,title,text_unit_ids,relationship_ids
0,9cc8da1b-91b5-48c3-a5a2-a9faba4bee44,0,Community 0,[2c778bf19dd747fb300d8456e3733f0a0c5627fce0208...,"[12a67f3d-b05a-4345-983b-a7d3e05f46c6, 3f464e4..."
1,58f19672-0af5-42e6-b5ea-e7aa3aaa25ef,0,Community 1,[b12a3853c3eacd2a9bf1ed14e37abe80bccc66891f6b7...,"[07b0da5c-3d50-4f12-bbc6-f3b0bf8f37a4, 1c55de4..."

In [113]:
statement = """
MERGE (c:__Community__ {community:value.id})
SET c += value {.level, .title}
/*
UNWIND value.text_unit_ids as text_unit_id
MATCH (t:__Chunk__ {id:text_unit_id})
MERGE (c)-[:HAS_CHUNK]->(t)
WITH distinct c, value
*/
WITH *
UNWIND value.relationship_ids as rel_id
MATCH (start:__Entity__)-[:RELATED {id:rel_id}]->(end:__Entity__)
MERGE (start)-[:IN_COMMUNITY]->(c)
MERGE (end)-[:IN_COMMUNITY]->(c)
RETURN count(distinct c) as createdCommunities
"""

batched_import(statement, community_df)

{'_contains_updates': True, 'labels_added': 546, 'relationships_created': 7213, 'nodes_created': 546, 'properties_set': 1638}
546 rows in 2.1788158416748047 s.

546

community_reports

In [114]:
community_report_df = pd.read_parquet(f'{GRAPHRAG_FOLDER}/create_final_community_reports.parquet',
                               columns=["id","community","level","title","summary", "findings","rank","rank_explanation","full_content"])
community_report_df.head(2)

,id,community,level,title,summary,findings,rank,rank_explanation,full_content
0,defd0c86911249ee8d675fd491a90566,534,3,Buddhist Monks and the Rain-Praying Contest,This community centers around the Buddhist mon...,[{'explanation': 'The Buddhist monks are the c...,7.5,The impact severity rating is high due to the ...,# Buddhist Monks and the Rain-Praying Contest\...
1,12bce1327f794e8ba176edc5d82b3c9d,535,3,Village Elders and Taoist Priests Community,This community is centered around the interact...,[{'explanation': 'The Village Elders are local...,7.5,The impact severity rating is high due to the ...,# Village Elders and Taoist Priests Community\...

In [115]:
# import communities
community_statement = """
MERGE (c:__Community__ {community:value.community})
SET c += value {.level, .title, .rank, .rank_explanation, .full_content, .summary}
WITH c, value
UNWIND range(0, size(value.findings)-1) AS finding_idx
WITH c, value, finding_idx, value.findings[finding_idx] as finding
MERGE (c)-[:HAS_FINDING]->(f:Finding {id:finding_idx})
SET f += finding
"""
batched_import(community_statement, community_report_df)

{'_contains_updates': True, 'labels_added': 3064, 'relationships_created': 2518, 'nodes_created': 3064, 'properties_set': 11376}
546 rows in 2.073991298675537 s.

546